# Generated by Django 5.1.4 on 2026-09-14 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_credit_limit_customer_payment_terms_days'),
        ('purchases', '0004_purchase_due_date'),
        ('sales', '0004_salesinvoice_warehouse'),
        ('suppliers', '0002_supplier_payment_terms_days'),
        ('tenants', '0006_backfill_collections_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_type', models.CharField(choices=[('customer', 'Customer'), ('supplier', 'Supplier')], max_length=10)),
                ('note', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_notes', to='customers.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_notes', to='sales.salesinvoice')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_notes', to='purchases.purchase')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_notes', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgeingBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('company', 'label')},
            },
        ),
        migrations.CreateModel(
            name='OverdueNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase', 'Purchase')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('bucket_label', models.CharField(max_length=30)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
            options={
                'unique_together': {('company', 'source_type', 'source_id', 'bucket_label')},
            },
        ),
    ]
