# Generated by Django 5.1.4 on 2026-09-08 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('employees', '0002_commission'),
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('returned', 'Returned')], default='in_stock', max_length=20)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sold_date', models.DateField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_units_bought', to='customers.customer')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycle_units', to='inventory.product')),
            ],
            options={
                'unique_together': {('company', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_description', models.CharField(blank=True, max_length=255)),
                ('issue_description', models.TextField()),
                ('received_date', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='received', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_tickets', to='customers.customer')),
                ('cycle_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cycle_shop.cycleunit')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
