# Generated by Django 5.1.4 on 2026-09-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_warehouse_address_warehouse_is_active_and_more'),
        ('sales', '0003_salesinvoice_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
    ]
