# Generated by Django 5.1.4 on 2026-09-14 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_block_expired_batch_sale_and_more'),
        ('sales', '0004_salesinvoice_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Phase 31: which batch this line sold from, when the product is batch-tracked — lets process_return() restore stock to the same batch where possible.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='serial',
            field=models.ForeignKey(blank=True, help_text='Phase 31: which specific unit this line sold, when the product is serial-tracked.', null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productserial'),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productbatch'),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='serial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productserial'),
        ),
    ]
