# Generated by Django 5.1.4 on 2026-09-16 11:28

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesinvoice_discount_approved_by_and_more'),
        ('tenants', '0009_backfill_discount_approval_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpayment',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='currency',
            field=models.CharField(default='QAR', max_length=3),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='customerpayment',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='currency',
            field=models.CharField(default='QAR', max_length=3),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transaction_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transaction_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transaction_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='transaction_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=3)),
                ('effective_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('is_manual', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('company', 'currency', 'effective_date')},
            },
        ),
    ]
