# Generated by Django 5.1.4 on 2026-09-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_customerpayment_base_amount_customerpayment_currency_and_more'),
        ('tenants', '0009_backfill_discount_approval_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='tax_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salesreturnline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('inclusive', models.BooleanField(default=False)),
                ('classification', models.CharField(choices=[('taxable', 'Taxable'), ('zero_rated', 'Zero Rated'), ('exempt', 'Exempt')], default='taxable', max_length=20)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.taxcode'),
        ),
        migrations.CreateModel(
            name='TaxScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='taxcode',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='sales.taxscheme'),
        ),
        migrations.AlterUniqueTogether(
            name='taxcode',
            unique_together={('company', 'code', 'effective_from')},
        ),
    ]
