# Generated by Django 5.1.4 on 2026-09-17 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journalentry_accounting__company_daa894_idx_and_more'),
        ('customers', '0003_customer_credit_limit_customer_payment_terms_days'),
        ('inventory', '0007_alter_stockmovement_reason'),
        ('sales', '0010_salesinvoice_tax_breakdown_and_more'),
        ('tenants', '0011_backfill_payroll_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'date', 'status'], name='sales_sales_company_e1383c_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['company', 'customer', 'due_date'], name='sales_sales_company_124221_idx'),
        ),
    ]
