# Generated by Django 5.1.4 on 2026-09-29 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0011_salesinvoice_sales_sales_company_e1383c_idx_and_more"),
        ("tenants", "0014_company_vat_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineSaleSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("offline", "Offline sale"), ("live", "Live till")],
                        default="offline",
                        help_text="'live' rows only remember a till request id, so a retried checkout never bills twice.",
                        max_length=8,
                    ),
                ),
                ("client_id", models.UUIDField()),
                ("offline_number", models.CharField(max_length=40)),
                ("device_created_at", models.DateTimeField(blank=True, null=True)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("attention", "Needs attention"),
                            ("resolved", "Resolved"),
                        ],
                        default="synced",
                        max_length=12,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_syncs",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "synced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "client_id"),
                        name="one_sync_per_offline_sale",
                    )
                ],
            },
        ),
    ]
