# Generated by Django 5.1.4 on 2026-09-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0012_offline_sale_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverynote",
            name="number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="quotation",
            name="number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="quotation",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="salesorder",
            name="number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
