# Generated by Django 5.1.4 on 2026-09-30 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_credit_limit_customer_payment_terms_days"),
        ("sales", "0013_document_numbers"),
        ("tenants", "0015_company_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnlinePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                ("transaction_id", models.CharField(max_length=64, unique=True)),
                ("gateway_payment_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("status_detail", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "receipts",
                    models.CharField(
                        blank=True,
                        help_text="Invoice numbers the payment was applied to.",
                        max_length=255,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online_payments",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="online_payments",
                        to="sales.salesinvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OnlinePaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Off"),
                            ("skipcash", "SkipCash (Qatar)"),
                            ("razorpay", "Razorpay (India)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("test_mode", models.BooleanField(default=True)),
                ("key_id", models.CharField(blank=True, max_length=255)),
                ("client_id", models.CharField(blank=True, max_length=255)),
                ("secret_ciphertext", models.TextField(blank=True)),
                ("webhook_key_ciphertext", models.TextField(blank=True)),
                (
                    "deposit_to",
                    models.CharField(
                        default="bank",
                        help_text="bank or cash — the ledger account payments land in.",
                        max_length=10,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Bank transfer / UPI / Fawran details shown to customers.",
                    ),
                ),
                ("portal_enabled", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company",)},
            },
        ),
    ]
