# Generated by Django 5.1.4 on 2026-10-08 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_salary_advances_hr_settings"),
        ("sales", "0014_online_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesinvoice",
            name="served_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff member who did the work (Billing screen).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="served_invoices",
                to="employees.employee",
            ),
        ),
    ]
