# Generated by Django 5.1.4 on 2026-09-17 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_credit_limit_customer_payment_terms_days'),
        ('inventory', '0007_alter_stockmovement_reason'),
        ('mobile_shop', '0001_initial'),
        ('purchases', '0009_purchase_purchases_p_company_2c4ab7_idx_and_more'),
        ('sales', '0011_salesinvoice_sales_sales_company_e1383c_idx_and_more'),
        ('tenants', '0012_companyonboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileunit',
            name='sale_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobile_unit', to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='mobileunit',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='MobileRepairJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=30)),
                ('device_description', models.CharField(max_length=255)),
                ('imei', models.CharField(blank=True, max_length=20)),
                ('reported_issue', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('work_done', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosing', 'Diagnosing'), ('waiting_parts', 'Waiting for Parts'), ('ready', 'Ready'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice')),
                ('mobile_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repair_jobs', to='mobile_shop.mobileunit')),
                ('service_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'status', 'received_at'], name='mobile_shop_company_a3bb6b_idx')],
                'unique_together': {('company', 'job_number')},
            },
        ),
        migrations.CreateModel(
            name='MobileTradeIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], default='used', max_length=20)),
                ('quoted_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('accepted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='quoted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.customer')),
                ('mobile_unit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile_shop.mobileunit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchase')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('company', 'imei')},
            },
        ),
    ]
