# Generated by Django 5.1.4 on 2026-09-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_category', models.CharField(choices=[('cricket', 'Cricket'), ('football', 'Football'), ('badminton', 'Badminton'), ('gym_equipment', 'Gym Equipment'), ('running', 'Running'), ('other', 'Other')], default='other', max_length=20)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('gender', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('kids', 'Kids')], default='unisex', max_length=10)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sports_detail', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
