# Generated by Django 5.1.4 on 2026-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_loyaltyaccount_loyaltytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 means no limit. Checked via apps.collections.services.customer_credit_status().', max_digits=14),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30, help_text='Default due-date offset for new invoices to this customer.'),
        ),
    ]
