# Generated by Django 5.1.4 on 2026-09-09 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginattempt'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='accounts_lo_identif_ee362a_idx',
            old_name='accounts_lo_identif_1a2b3c_idx',
        ),
    ]
