# Generated by Django 5.1.4 on 2026-09-29 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_rename_accounts_lo_identif_1a2b3c_idx_accounts_lo_identif_ee362a_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TwoFactorDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secret_encrypted", models.TextField()),
                ("confirmed", models.BooleanField(default=False)),
                ("recovery_code_hashes", models.JSONField(blank=True, default=list)),
                ("last_used_step", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="two_factor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
