# Generated by Django 5.1.4 on 2026-09-07 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_modules', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='companymodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module'),
        ),
        migrations.AddField(
            model_name='businesstypedefaultmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.module'),
        ),
        migrations.AlterUniqueTogether(
            name='companymodule',
            unique_together={('company', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='businesstypedefaultmodule',
            unique_together={('business_type', 'module')},
        ),
    ]
