# Generated by Django 5.1.4 on 2026-09-23 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_enabled', models.BooleanField(default=False)),
                ('stripe_test_mode', models.BooleanField(default=True)),
                ('stripe_publishable_key_ciphertext', models.TextField(blank=True)),
                ('stripe_secret_key_ciphertext', models.TextField(blank=True)),
                ('stripe_webhook_secret_ciphertext', models.TextField(blank=True)),
                ('razorpay_enabled', models.BooleanField(default=False)),
                ('razorpay_test_mode', models.BooleanField(default=True)),
                ('razorpay_key_id_ciphertext', models.TextField(blank=True)),
                ('razorpay_key_secret_ciphertext', models.TextField(blank=True)),
                ('razorpay_webhook_secret_ciphertext', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment gateway settings',
            },
        ),
    ]
