# Generated by Django 5.1.4 on 2026-09-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_admin", "0002_paymentgatewaysettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentgatewaysettings",
            name="skipcash_client_id_ciphertext",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentgatewaysettings",
            name="skipcash_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="paymentgatewaysettings",
            name="skipcash_key_id_ciphertext",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentgatewaysettings",
            name="skipcash_key_secret_ciphertext",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="paymentgatewaysettings",
            name="skipcash_test_mode",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentgatewaysettings",
            name="skipcash_webhook_key_ciphertext",
            field=models.TextField(blank=True),
        ),
    ]
