# Generated by Django 5.1.4 on 2026-10-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def first_messages(apps, schema_editor):
    """Older tickets keep their text in SupportTicket.message; make it the first chat message."""
    Ticket = apps.get_model("platform_admin", "SupportTicket")
    Message = apps.get_model("platform_admin", "SupportMessage")
    for t in Ticket.objects.all():
        if t.message and not Message.objects.filter(ticket=t).exists():
            m = Message.objects.create(ticket=t, sender_id=t.raised_by_id, body=t.message)
            Message.objects.filter(pk=m.pk).update(created_at=t.created_at)
        Ticket.objects.filter(pk=t.pk).update(last_message_at=t.created_at)


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_admin",
            "0003_paymentgatewaysettings_skipcash_client_id_ciphertext_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supportticket",
            name="admin_unread",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="client_unread",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="supportticket",
            name="last_message_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_admin", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="platform_admin.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.RunPython(first_messages, migrations.RunPython.noop),
    ]
