# Generated by Django 5.1.4 on 2026-09-29 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounting", "0003_journalentry_accounting__company_daa894_idx_and_more"),
        ("customers", "0003_customer_credit_limit_customer_payment_terms_days"),
        ("inventory", "0008_product_boutique_attributes"),
        ("purchases", "0009_purchase_purchases_p_company_2c4ab7_idx_and_more"),
        ("sales", "0011_salesinvoice_sales_sales_company_e1383c_idx_and_more"),
        ("suppliers", "0002_supplier_payment_terms_days"),
        ("tenants", "0013_companybusinesstype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Kitchen equipment, Vehicles, Furniture",
                        max_length=80,
                    ),
                ),
                ("asset_code", models.CharField(blank=True, max_length=40)),
                ("purchase_date", models.DateField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "salvage_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("useful_life_months", models.PositiveIntegerField(default=60)),
                (
                    "paid_from",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("cash", "Cash"),
                            ("payable", "On credit (supplier)"),
                            ("none", "Already owned (no payment now)"),
                        ],
                        default="bank",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "In use"), ("disposed", "Disposed")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("disposed_on", models.DateField(blank=True, null=True)),
                (
                    "disposal_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "purchase_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="PostDatedCheque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("received", "Received from customer"),
                            ("issued", "Issued to supplier"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cheque_number", models.CharField(max_length=40)),
                ("bank_name", models.CharField(blank=True, max_length=120)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "cheque_date",
                    models.DateField(
                        help_text="Date written on the cheque (when it can be cashed)."
                    ),
                ),
                ("received_on", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("deposited", "Deposited"),
                            ("cleared", "Cleared"),
                            ("bounced", "Bounced"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("deposited_on", models.DateField(blank=True, null=True)),
                ("cleared_on", models.DateField(blank=True, null=True)),
                ("bounce_reason", models.CharField(blank=True, max_length=255)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("reminder_sent_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdcs",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pdcs",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pdcs",
                        to="purchases.purchase",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pdcs",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["cheque_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Monthly maintenance contract", max_length=120
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Every 3 months"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=10,
                    ),
                ),
                ("next_run_date", models.DateField()),
                (
                    "anchor_day",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Day of month to bill on (keeps 31st billing at month end).",
                    ),
                ),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("email_customer", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("invoices_created", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recurring_invoices",
                        to="customers.customer",
                    ),
                ),
                (
                    "last_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="RecurringInvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=1, max_digits=12),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "recurring",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.recurringinvoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepreciationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_end", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "journal_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounting.journalentry",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_entries",
                        to="finance.fixedasset",
                    ),
                ),
            ],
            options={
                "ordering": ["period_end"],
                "unique_together": {("asset", "period_end")},
            },
        ),
    ]
