# Generated by Django 5.1.4 on 2026-09-13 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_is_stock_tracked'),
        ('sales', '0004_salesinvoice_warehouse'),
        ('vehicle_wash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='washorder',
            name='sales_invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice'),
        ),
        migrations.AddField(
            model_name='washpackage',
            name='product',
            field=models.OneToOneField(blank=True, help_text='The service Product that complete_wash() invoices against — see vehicle_wash.services.create_wash_package.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wash_package', to='inventory.product'),
        ),
    ]
