# Generated by Django 5.1.4 on 2026-09-09 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='product',
            field=models.OneToOneField(blank=True, help_text='The service Product that enroll_member() invoices against — see gym.services.create_membership_plan.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gym_membership_plan', to='inventory.product'),
        ),
    ]
