# Generated by Django 5.1.4 on 2026-09-17 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_fiscalyear_options_fiscalyear_closed_at_and_more'),
        ('tenants', '0011_backfill_payroll_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'date', 'is_void'], name='accounting__company_daa894_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['company', 'source_type', 'source_id'], name='accounting__company_67b2a4_idx'),
        ),
    ]
