# Generated by Django 5.1.4 on 2026-09-17 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_backfill_payroll_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_profile_complete', models.BooleanField(default=False)),
                ('accounting_setup_complete', models.BooleanField(default=False)),
                ('branch_setup_complete', models.BooleanField(default=False)),
                ('products_setup_complete', models.BooleanField(default=False)),
                ('team_setup_complete', models.BooleanField(default=False)),
                ('tax_setup_complete', models.BooleanField(default=False)),
                ('opening_balances_complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='tenants.company')),
            ],
        ),
    ]
