# Generated by Django 5.1.4 on 2026-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0013_companybusinesstype"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="vat_number",
            field=models.CharField(
                blank=True,
                help_text="Tax registration number printed on invoices (VAT TRN, KSA VAT no., India GSTIN).",
                max_length=30,
            ),
        ),
    ]
