# Generated by Django 5.1.4 on 2026-09-29 18:04

from django.db import migrations, models
from django.utils import timezone


def existing_companies_are_set_up(apps, schema_editor):
    # Only new sign-ups should see the setup wizard.
    apps.get_model("tenants", "Company").objects.update(onboarding_completed_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_company_vat_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="onboarding_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when the owner finishes or skips the first-run setup wizard.",
                null=True,
            ),
        ),
        migrations.RunPython(existing_companies_are_set_up, migrations.RunPython.noop),
    ]
