# Generated by Django 5.1.4 on 2026-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_product_boutique_attributes"),
        ("tenants", "0015_company_onboarding"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymembership",
            name="warehouses",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="inventory.warehouse"
            ),
        ),
    ]
