# Generated by Django 5.1.4 on 2026-10-04 11:35

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0016_membership_branches"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company_logos/",
                validators=[apps.common.validators.validate_upload_file],
            ),
        ),
    ]
