# Generated by Django 5.1.4 on 2026-10-04 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_upload_limits"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackupSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "keep_days",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (7, "7 days"),
                            (14, "14 days"),
                            (30, "30 days"),
                            (90, "90 days"),
                        ],
                        default=14,
                    ),
                ),
                ("include_media", models.BooleanField(default=False)),
                ("drive_enabled", models.BooleanField(default=False)),
                ("drive_refresh_token", models.TextField(blank=True)),
                ("drive_email", models.CharField(blank=True, max_length=254)),
                ("drive_folder_id", models.CharField(blank=True, max_length=128)),
                ("drive_error", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_settings",
                        to="tenants.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyBackup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        default="auto",
                        max_length=10,
                    ),
                ),
                ("status", models.CharField(default="ok", max_length=10)),
                ("file_name", models.CharField(blank=True, max_length=255)),
                ("size", models.PositiveBigIntegerField(default=0)),
                ("rows", models.PositiveIntegerField(default=0)),
                ("tables", models.PositiveIntegerField(default=0)),
                ("include_media", models.BooleanField(default=False)),
                ("drive_file_id", models.CharField(blank=True, max_length=128)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backups",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "-created_at"],
                        name="tenants_com_company_4d11c1_idx",
                    )
                ],
            },
        ),
    ]
