# Generated by Django 5.1.4 on 2026-10-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0019_settings_and_reports_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyonboarding",
            name="milestones",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
