# Generated by Django 5.1.4 on 2026-10-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0020_onboarding_milestones"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_demo",
            field=models.BooleanField(default=False),
        ),
    ]
