# Generated by Django 5.1.4 on 2026-09-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='country',
            field=models.CharField(default='Global', help_text='Which country/region this price applies to', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(default='QAR', max_length=3),
        ),
    ]
