# Generated by Django 5.1.4 on 2026-09-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionplan_country_subscriptionplan_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='submitted_by_client',
            field=models.BooleanField(default=False),
        ),
    ]
