# Generated by Django 5.1.4 on 2026-09-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionpayment_is_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='downgrade_effective_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='grace_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='grace_period_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_invoices_per_month',
            field=models.PositiveIntegerField(default=0, help_text='0 means unlimited'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_warehouses',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(default=0, help_text='0 means not enforced'),
        ),
    ]
