# Generated by Django 5.1.4 on 2026-09-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_gatewaycheckout"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("standard", "Normal business"),
                    ("large", "Supermarket / large shop"),
                ],
                default="standard",
                help_text="Which businesses this price is for; see apps/subscriptions/pricing.py.",
                max_length=10,
            ),
        ),
    ]
