# Generated by Django 5.1.4 on 2026-10-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0007_plan_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="extra_branch_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price per year for each branch above max_warehouses. 0 = branches are free.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="extra_user_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price per year for each user above max_users. 0 = no extra users (upgrade the plan instead).",
                max_digits=10,
            ),
        ),
    ]
