from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("construction", "0001_initial"), ("employees", "0004_payrollperiod_payrollrun_salarystructure_and_more")]
    operations = [
        migrations.CreateModel(name="ProjectMilestone", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=200)), ("due_date", models.DateField(blank=True, null=True)), ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)), ("status", models.CharField(choices=[("pending", "Pending"), ("in_progress", "In Progress"), ("completed", "Completed"), ("invoiced", "Invoiced")], default="pending", max_length=20)), ("completion_percent", models.PositiveIntegerField(default=0)), ("notes", models.TextField(blank=True)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.company")), ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="milestones", to="construction.project"))]),
        migrations.CreateModel(name="ProjectTask", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=200)), ("due_date", models.DateField(blank=True, null=True)), ("status", models.CharField(choices=[("todo", "To Do"), ("in_progress", "In Progress"), ("blocked", "Blocked"), ("done", "Done")], default="todo", max_length=20)), ("priority", models.CharField(default="normal", max_length=20)), ("description", models.TextField(blank=True)), ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="employees.employee")), ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.company")), ("milestone", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="construction.projectmilestone")), ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="construction.project"))]),
        migrations.CreateModel(name="ProjectTimesheet", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("date", models.DateField()), ("hours", models.DecimalField(decimal_places=2, max_digits=6)), ("hourly_rate", models.DecimalField(decimal_places=2, default=0, max_digits=10)), ("description", models.CharField(blank=True, max_length=255)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.company")), ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="employees.employee")), ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="timesheets", to="construction.project")), ("task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="timesheets", to="construction.projecttask"))]),
    ]
