"""
Courses, enrollments, fees and attendance for schools, tuition centres,
nurseries and driving schools.

Monthly fees are generated once per student and month: one invoice per
student listing every course they attend, so parents get a single bill.
A FeeCharge row per enrollment and month makes the run safe to repeat.
"""
import calendar
from collections import defaultdict
from datetime import date
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.db.models import F, Sum

from .common import invoice as make_invoice, money, service_product
from .models import AttendanceMark, AttendanceSession, Course, Enrollment, FeeCharge


def month_key(day):
    return f"{day.year:04d}-{day.month:02d}"


def month_bounds(key):
    year, month = (int(x) for x in key.split("-"))
    return date(year, month, 1), date(year, month, calendar.monthrange(year, month)[1])


def course_product(course):
    product = service_product(course.company, f"COURSE-{course.pk}", course.name, course.fee)
    if course.product_id != product.pk:
        Course.objects.filter(pk=course.pk).update(product=product)
        course.product = product
    return product


@transaction.atomic
def enroll(*, company, user, course, student, start_date, discount_percent=0, guardian_name="", guardian_phone="",
           notes="", bill_now=True):
    course = Course.objects.select_for_update().get(pk=course.pk, company=company)
    if not course.is_active:
        raise ValidationError(f"{course.name} is closed for enrolment.")
    if Enrollment.objects.filter(company=company, course=course, student=student, status="active").exists():
        raise ValidationError(f"{student.name} is already enrolled in {course.name}.")
    if course.capacity and course.enrollments.filter(status="active").count() >= course.capacity:
        raise ValidationError(f"{course.name} is full ({course.capacity}).")
    discount = Decimal(str(discount_percent or 0))
    if not Decimal("0") <= discount <= Decimal("100"):
        raise ValidationError("Discount must be between 0 and 100%.")
    enrollment = Enrollment.objects.create(
        company=company, student=student, course=course, start_date=start_date, discount_percent=discount,
        guardian_name=guardian_name, guardian_phone=guardian_phone, notes=notes)
    if bill_now:
        period = "once" if course.billing == "once" else month_key(start_date)
        bill(company=company, user=user, enrollments=[enrollment], period=period, on=start_date)
    return enrollment


def withdraw(enrollment, *, end_date, status="withdrawn"):
    if enrollment.status != "active":
        raise ValidationError("This enrolment is already closed.")
    enrollment.status, enrollment.end_date = status, end_date
    enrollment.save(update_fields=["status", "end_date"])
    return enrollment


def _billable(enrollments, period):
    already = set(FeeCharge.objects.filter(enrollment__in=enrollments, period=period).values_list("enrollment_id", flat=True))
    return [e for e in enrollments if e.pk not in already and e.fee > 0]


@transaction.atomic
def bill(*, company, user, enrollments, period, on=None):
    """Invoices the given enrollments for one period, one invoice per student. Returns the invoices."""
    todo = _billable(enrollments, period)
    by_student = defaultdict(list)
    for e in todo:
        by_student[e.student_id].append(e)
    invoices = []
    for rows in by_student.values():
        lines = [(course_product(e.course), Decimal("1"), e.fee) for e in rows]
        inv = make_invoice(company, user, rows[0].student, lines, date=on)
        for e in rows:
            try:
                with transaction.atomic():
                    FeeCharge.objects.create(company=company, enrollment=e, period=period, amount=e.fee, invoice=inv)
            except IntegrityError:
                raise ValidationError("These fees were just generated by someone else. Refresh and try again.")
        invoices.append(inv)
    return invoices


def due_for_month(company, key):
    """Active monthly enrollments running in that month that haven't been billed yet."""
    first, last = month_bounds(key)
    candidates = list(Enrollment.objects.for_company(company).filter(
        status="active", course__billing="monthly", start_date__lte=last).select_related("course", "student"))
    return _billable(candidates, key)


def generate_month(*, company, user, key, on=None):
    first, _ = month_bounds(key)
    return bill(company=company, user=user, enrollments=due_for_month(company, key), period=key, on=on or first)


def dues(company):
    """Unpaid fee invoices per student, oldest first."""
    invoice_ids = FeeCharge.objects.for_company(company).exclude(invoice=None).values_list("invoice_id", flat=True)
    from apps.sales.models import SalesInvoice
    unpaid = (SalesInvoice.objects.for_company(company).filter(id__in=invoice_ids, amount_paid__lt=F("total"))
              .select_related("customer").order_by("date"))
    students = {}
    for inv in unpaid:
        row = students.setdefault(inv.customer_id, {"student": inv.customer, "invoices": [], "due": Decimal("0")})
        row["invoices"].append(inv)
        row["due"] += inv.total - inv.amount_paid
    return sorted(students.values(), key=lambda r: -r["due"])


@transaction.atomic
def take_attendance(*, company, user, course, day, present_ids):
    session, _ = AttendanceSession.objects.get_or_create(company=company, course=course, date=day,
                                                         defaults={"taken_by": user})
    present_ids = {int(x) for x in present_ids}
    active = course.enrollments.filter(status="active", start_date__lte=day)
    for e in active:
        AttendanceMark.objects.update_or_create(session=session, enrollment=e, defaults={"present": e.pk in present_ids})
    return session


def attendance_rates(course):
    """{enrollment_id: (present, total)} over all sessions taken."""
    rates = defaultdict(lambda: [0, 0])
    for mark in AttendanceMark.objects.filter(session__course=course).values("enrollment_id", "present"):
        rates[mark["enrollment_id"]][1] += 1
        if mark["present"]:
            rates[mark["enrollment_id"]][0] += 1
    return {k: tuple(v) for k, v in rates.items()}


def month_summary(company, key):
    charges = FeeCharge.objects.for_company(company).filter(period=key).select_related("invoice")
    billed = charges.aggregate(t=Sum("amount"))["t"] or Decimal("0")
    invoices = {c.invoice_id: c.invoice for c in charges if c.invoice_id}
    collected = sum((min(i.amount_paid, i.total) for i in invoices.values()), Decimal("0"))
    return {"billed": billed, "collected": collected, "outstanding": billed - collected, "count": len(invoices)}
