"""
Property management: buildings, units, tenancy contracts and monthly rent.

A unit can only have one active lease at a time. The monthly rent run bills
every lease that covers the month, once (RentCharge per lease and month).
"""
from datetime import date, timedelta
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.db import IntegrityError, transaction
from django.db.models import F, Sum
from django.utils import timezone

from .common import invoice as make_invoice, money, service_product
from .education import month_bounds, month_key
from .models import Lease, RentalUnit, RentCharge


def unit_product(unit):
    product = service_product(unit.company, f"RENT-{unit.pk}", f"Rent · {unit.property.name} {unit.name}", unit.monthly_rent)
    if unit.product_id != product.pk:
        RentalUnit.objects.filter(pk=unit.pk).update(product=product)
        unit.product = product
    return product


def overlapping(unit, start, end, exclude=None):
    qs = Lease.objects.filter(unit=unit, status="active", start_date__lte=end, end_date__gte=start)
    return qs.exclude(pk=exclude.pk) if exclude else qs


@transaction.atomic
def create_lease(*, company, user, unit, tenant, start_date, end_date, monthly_rent, due_day=1, security_deposit=0,
                 notes="", bill_first_month=True):
    unit = RentalUnit.objects.select_for_update().select_related("property").get(pk=unit.pk, company=company)
    if end_date <= start_date:
        raise ValidationError("The lease must end after it starts.")
    rent = money(monthly_rent, "rent")
    if rent <= 0:
        raise ValidationError("Enter the monthly rent.")
    if not 1 <= int(due_day) <= 28:
        raise ValidationError("Rent due day must be between 1 and 28.")
    clash = overlapping(unit, start_date, end_date).select_related("tenant").first()
    if clash:
        raise ValidationError(f"{unit} is already leased to {clash.tenant.name} until {clash.end_date:%d %b %Y} ({clash.number}).")
    lease = Lease.objects.create(company=company, unit=unit, tenant=tenant, start_date=start_date, end_date=end_date,
                                 monthly_rent=rent, due_day=int(due_day), security_deposit=money(security_deposit, "deposit"),
                                 notes=notes, created_by=user)
    lease.number = f"LS-{lease.pk:05d}"
    lease.save(update_fields=["number"])
    if bill_first_month:
        bill(company=company, user=user, leases=[lease], key=month_key(start_date))
    return lease


def end_lease(lease, *, on, early=False):
    if lease.status != "active":
        raise ValidationError("This lease is already closed.")
    lease.status = "terminated" if early else "ended"
    lease.ended_on = on
    if early and on < lease.end_date:
        lease.end_date = on
    lease.save(update_fields=["status", "ended_on", "end_date"])
    return lease


def _due_date(lease, key):
    first, last = month_bounds(key)
    return min(first + timedelta(days=lease.due_day - 1), last)


def leases_for_month(company, key):
    first, last = month_bounds(key)
    leases = list(Lease.objects.for_company(company).filter(status="active", start_date__lte=last, end_date__gte=first)
                  .select_related("unit__property", "tenant"))
    billed = set(RentCharge.objects.filter(lease__in=leases, period=key).values_list("lease_id", flat=True))
    return [l for l in leases if l.pk not in billed]


@transaction.atomic
def bill(*, company, user, leases, key):
    invoices = []
    for lease in leases:
        if RentCharge.objects.filter(lease=lease, period=key).exists():
            continue
        due = _due_date(lease, key)
        inv = make_invoice(company, user, lease.tenant, [(unit_product(lease.unit), Decimal("1"), lease.monthly_rent)],
                           date=month_bounds(key)[0])
        if inv.due_date != due:
            inv.due_date = due
            inv.save(update_fields=["due_date"])
        try:
            with transaction.atomic():
                RentCharge.objects.create(company=company, lease=lease, period=key, amount=lease.monthly_rent,
                                          due_date=due, invoice=inv)
        except IntegrityError:
            raise ValidationError("Rent for this month was just generated by someone else. Refresh and try again.")
        invoices.append(inv)
    return invoices


def generate_month(*, company, user, key):
    return bill(company=company, user=user, leases=leases_for_month(company, key), key=key)


def overdue(company, today=None):
    """Unpaid rent past its due date, with days late."""
    today = today or timezone.localdate()
    charges = (RentCharge.objects.for_company(company).filter(due_date__lt=today, invoice__amount_paid__lt=F("invoice__total"))
               .select_related("lease__tenant", "lease__unit__property", "invoice").order_by("due_date"))
    return [{"charge": c, "due": c.invoice.total - c.invoice.amount_paid, "days": (today - c.due_date).days} for c in charges]


def summary(company, today=None):
    today = today or timezone.localdate()
    units = RentalUnit.objects.for_company(company).filter(is_active=True)
    active = Lease.objects.for_company(company).filter(status="active", start_date__lte=today, end_date__gte=today)
    occupied_ids = set(active.values_list("unit_id", flat=True))
    key = month_key(today)
    charges = RentCharge.objects.for_company(company).filter(period=key).select_related("invoice")
    billed = charges.aggregate(t=Sum("amount"))["t"] or Decimal("0")
    collected = sum((min(c.invoice.amount_paid, c.invoice.total) for c in charges if c.invoice_id), Decimal("0"))
    unit_count = units.count()
    return {
        "units": unit_count, "occupied": len(occupied_ids), "vacant": unit_count - len(occupied_ids),
        "occupancy": round(len(occupied_ids) * 100 / unit_count) if unit_count else 0,
        "rent_roll": active.aggregate(t=Sum("monthly_rent"))["t"] or Decimal("0"),
        "billed": billed, "collected": collected, "month": key,
        "occupied_ids": occupied_ids,
        "expiring": list(Lease.objects.for_company(company).filter(status="active", end_date__gte=today,
                                                                   end_date__lte=today + timedelta(days=60))
                         .select_related("tenant", "unit__property").order_by("end_date")),
        "not_billed": len(leases_for_month(company, key)),
    }
