from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("saloon", "0002_saloonservice_product_servicepackage_product"), ("employees", "0004_payrollperiod_payrollrun_salarystructure_and_more"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="ServiceClientProfile", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("profile_type", models.CharField(choices=[("person", "Person / Patient"), ("student", "Student"), ("pet", "Pet"), ("vehicle", "Vehicle"), ("asset", "Asset / Item"), ("organization", "Organization")], default="person", max_length=20)), ("subject_name", models.CharField(max_length=200)), ("reference_code", models.CharField(blank=True, max_length=50)), ("date_of_birth", models.DateField(blank=True, null=True)), ("identifier", models.CharField(blank=True, help_text="MRN, student ID, plate, asset tag, etc.", max_length=100)), ("details", models.JSONField(blank=True, default=dict)), ("notes", models.TextField(blank=True)), ("is_active", models.BooleanField(default=True)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.company")), ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="service_profiles", to="customers.customer"))], options={"unique_together": {("company", "reference_code")}}),
        migrations.CreateModel(name="ServiceCase", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=200)), ("case_type", models.CharField(blank=True, max_length=100)), ("description", models.TextField(blank=True)), ("status", models.CharField(choices=[("open", "Open"), ("in_progress", "In Progress"), ("waiting", "Waiting"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="open", max_length=20)), ("opened_date", models.DateField()), ("due_date", models.DateField(blank=True, null=True)), ("closed_date", models.DateField(blank=True, null=True)), ("assigned_staff", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="employees.employee")), ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.company")), ("profile", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cases", to="saloon.serviceclientprofile"))]),
        migrations.CreateModel(name="ServiceCaseNote", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("date", models.DateField()), ("note_type", models.CharField(blank=True, help_text="Diagnosis, lesson, repair update, collection, etc.", max_length=50)), ("notes", models.TextField()), ("outcome", models.TextField(blank=True)), ("next_follow_up", models.DateField(blank=True, null=True)), ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="case_notes", to="saloon.servicecase")), ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="tenants.company")), ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL))]),
    ]
