# Generated by Django 5.1.4 on 2026-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=30, help_text='Default due-date offset for new bills from this supplier.'),
        ),
    ]
