# Generated by Django 5.1.4 on 2026-09-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_parlour', '0001_initial'),
        ('inventory', '0004_product_is_stock_tracked'),
    ]

    operations = [
        migrations.AddField(
            model_name='beautyservice',
            name='product',
            field=models.OneToOneField(blank=True, help_text='The service Product that book_appointment() invoices a walk-in against — see beauty_parlour.services.create_beauty_service.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beauty_service', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='product',
            field=models.OneToOneField(blank=True, help_text='The service Product that purchase_package() invoices against — see beauty_parlour.services.create_service_package.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beauty_service_package', to='inventory.product'),
        ),
    ]
