# Generated by Django 5.1.4 on 2026-09-10 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Free-form spec details (material, warranty, weight...) as key/value pairs.'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Set if this row is a variant (e.g. a specific size/color) of another product.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_label',
            field=models.CharField(blank=True, help_text="e.g. 'Red / M' — only meaningful when parent is set.", max_length=100),
        ),
    ]
