# Generated by Django 5.1.4 on 2026-09-14 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_is_stock_tracked'),
        ('tenants', '0006_backfill_collections_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='block_expired_batch_sale',
            field=models.BooleanField(default=True, help_text='Batch-tracked products only: if True, selling from a batch whose expiry_date has passed is rejected outright rather than just warned about.'),
        ),
        migrations.AddField(
            model_name='product',
            name='tracking_type',
            field=models.CharField(choices=[('none', 'None'), ('basic', 'Basic Stock'), ('batch', 'Batch/Lot'), ('serial', 'Serial Number')], default='basic', help_text="Phase 31: how granularly this product's stock is tracked. Only meaningful when is_stock_tracked=True — ignored (treated as 'none') for service products. 'basic' is the pre-Phase-31 behaviour (aggregate quantity only, what every existing product effectively had). 'batch' requires selecting/recording a ProductBatch on every stock movement; 'serial' requires a ProductSerial.", max_length=10),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return', 'Return'), ('stock_count', 'Stock Count Adjustment')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacture_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.product')),
            ],
            options={
                'ordering': ['expiry_date'],
                'unique_together': {('company', 'product', 'batch_number')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch',
            field=models.ForeignKey(blank=True, help_text="Phase 31: set only for tracking_type='batch' products. Existing rows from before this phase are NULL, and aggregate current_stock() sums regardless.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.productbatch'),
        ),
        migrations.CreateModel(
            name='ProductSerial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('returned', 'Returned')], default='in_stock', max_length=10)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'unique_together': {('company', 'product', 'serial_number')},
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='serial',
            field=models.ForeignKey(blank=True, help_text="Phase 31: set only for tracking_type='serial' products (always ±1 quantity).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.productserial'),
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('stock_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
            ],
        ),
        migrations.CreateModel(
            name='BatchAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('near_expiry', 'Near Expiry'), ('expired', 'Expired')], max_length=15)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='inventory.productbatch')),
            ],
            options={
                'unique_together': {('company', 'batch', 'alert_type')},
            },
        ),
    ]
