# Generated by Django 5.1.4 on 2026-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_block_expired_batch_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return', 'Return'), ('stock_count', 'Stock Count Adjustment'), ('goods_receipt', 'Goods Receipt (PO)')], max_length=20),
        ),
    ]
