# Generated by Django 5.1.4 on 2026-10-08 10:48

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_product_boutique_attributes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Photo shown on the POS and website. Without one, a picture is chosen from the name.",
                null=True,
                upload_to="products/",
                validators=[apps.common.validators.validate_upload_file],
            ),
        ),
    ]
