"""Example values shown as placeholders ("e.g. …") in forms. Data only — see form_hints for how they are applied."""

FAMILIES = {
    "restaurant": {"restaurant", "cafe_juice_shop", "catering_company", "bakery"},
    "beauty": {"saloon", "beauty_parlour", "spa", "cosmetics_store", "perfume_shop"},
    "mobile": {"mobile_shop", "mobile_accessories_shop", "electronics_store", "computer_shop", "home_appliances_store",
               "electronics_repair", "computer_repair"},
    "fashion": {"clothing_store", "ladies_fashion_boutique", "textile", "footwear_store", "uniform_shop"},
    "grocery": {"grocery_store", "supermarket", "fruits_vegetables_shop", "fish_meat_shop", "general_retail", "retail_shop",
                "wholesale_business", "trading_company", "import_export", "ecommerce_store", "agricultural_supplies_store"},
    "pharmacy": {"medical_shop", "protein_shop", "medical_equipment_store", "optical_shop", "medical_clinic", "dental_clinic",
                 "physiotherapy_center", "diagnostic_laboratory", "veterinary_clinic", "home_nursing"},
    "jewelry": {"jewelry_shop", "watch_shop"},
    "auto": {"auto_spare_parts", "tyre_battery_shop", "car_showroom", "auto_garage", "vehicle_wash", "fuel_station", "car_rental"},
    "hardware": {"hardware_store", "building_materials_store", "electrical_plumbing_store", "construction", "furniture_store",
                 "kitchenware_store", "manufacturing", "industrial_services"},
    "books": {"book_store", "printing_shop", "toys_gift_shop", "baby_products_store", "flower_shop", "pet_shop",
              "musical_instruments_store"},
    "sports": {"sports_shop", "cycle_shop", "gym"},
}

# product, category, brand, sku, description
PRODUCT_SAMPLES = {
    "restaurant": ("Chicken Biryani", "Biryani", "House special", "BIR-001",
                   "Fragrant basmati rice slow-cooked with tender chicken and spices"),
    "beauty": ("Keratin hair treatment", "Hair care", "L'Oréal", "HC-001", "Smooth, frizz-free hair for up to 3 months"),
    "mobile": ("Samsung Galaxy A15 128GB", "Mobiles", "Samsung", "SAM-A15-128", "6.5\" display, 50MP camera, 5000 mAh"),
    "fashion": ("Men's cotton kandura", "Kandura", "Al Jazeera", "KAN-001", "Soft cotton, regular fit"),
    "grocery": ("Almarai full fat milk 1L", "Dairy", "Almarai", "6281007000017", "Fresh full-cream milk"),
    "pharmacy": ("Panadol Extra 24 tablets", "Pain relief", "GSK", "PAN-24", "For headache and fever"),
    "jewelry": ("22K gold bangle", "Bangles", "Malabar", "GB-22-001", "Hand-crafted 22 karat gold bangle"),
    "auto": ("Toyota brake pads (front)", "Brakes", "Toyota", "04465-0K240", "Genuine front brake pad set"),
    "hardware": ("Jotun interior paint 18L", "Paints", "Jotun", "JOT-18L-WH", "Washable matt finish, white"),
    "books": ("The Alchemist – Paulo Coelho", "Fiction", "HarperCollins", "9780062315007", "Paperback, 208 pages"),
    "sports": ("Nike running shoes", "Running", "Nike", "NK-RUN-42", "Lightweight cushioning for daily runs"),
    "default": ("Product name", "General", "Brand name", "SKU-1001", "Short description customers will see"),
}

# "name" boxes on these pages (matched against the start of the URL path)
NAME_BY_PATH = [
    ("/branches/", "Main branch – Al Sadd"), ("/units/", "pcs"), ("/mobile-shop/units/add", None),
    ("/restaurant/areas/", "Family hall"), ("/restaurant/tables/", "T1"), ("/spa/services/", "Swedish massage – 60 min"),
    ("/saloon/services/", "Haircut & beard trim"), ("/beauty-parlour/services/", "Bridal makeup"),
    ("/vehicle-wash/packages/", "Premium wash + wax"), ("/gym/plans/", "Monthly – Gold"),
    ("/education/courses/", "Spoken English – Level 1"), ("/bookings/resources/", "Sea view suite 101"),
    ("/property/", "Al Sadd Tower"), ("/textile/fabrics/", "Italian linen – white"),
    ("/construction/projects/", "Villa fit-out – Lusail"), ("/construction/contractors/", "Al Habtoor Electrical"),
    ("/finance/assets/", "Delivery van – Toyota Hiace"), ("/finance/recurring/", "Monthly office rent"),
    ("/crm/", "Ahmed Al-Kuwari"), ("/staff/leave/", "Annual leave"), ("/service-suite/packages/", "10-session package"),
    ("/expenses/categories/", "Rent"), ("/roles/", "Cashier"), ("/coupons/", "Eid offer"), ("/pricing/", "Eid offer 20%"),
    ("/brands/", None), ("/mobile-shop/categories/", None), ("/customers/", "Ahmed Al-Kuwari"),
    ("/suppliers/", "Al Meera Wholesale"), ("/staff/", "Ahmed Al-Kuwari"), ("/recruitment/", "Ahmed Al-Kuwari"),
]

FIELD_SAMPLES = {
    # people & contact
    "email": "name@example.com", "contact_email": "name@example.com", "emails": "owner@example.com, manager@example.com",
    "phone": "+974 5555 1234", "mobile": "+974 5555 1234", "whatsapp": "+974 5555 1234", "contact_phone": "+974 5555 1234",
    "alternate_phone": "+974 6666 4321", "customer_phone": "+974 5555 1234", "delivery_phone": "+974 5555 1234",
    "new_client_phone": "+974 5555 1234", "new_customer_phone": "+974 5555 1234", "new_student_phone": "+974 5555 1234",
    "new_tenant_phone": "+974 5555 1234", "guardian_phone": "+974 5555 1234",
    "first_name": "Ahmed", "last_name": "Al-Kuwari", "full_name": "Ahmed Al-Kuwari", "contact_name": "Ahmed Al-Kuwari",
    "customer_name": "Ahmed Al-Kuwari", "contact_person": "Ahmed Al-Kuwari", "guest_name": "Ahmed Al-Kuwari",
    "new_client_name": "Al Noor Trading WLL", "new_customer_name": "Ahmed Al-Kuwari", "new_student_name": "Aisha Mohammed",
    "new_tenant_name": "Ahmed Al-Kuwari", "guardian_name": "Mohammed Ali", "owner_name": "Ahmed Al-Kuwari",
    "manager_name": "Rashid Khan", "subject_name": "Ahmed Al-Kuwari", "teacher": "Ms. Fatima", "username": "cashier1",
    "company_name": "Al Noor Trading WLL", "business_name": "Al Noor Trading WLL", "organization_name": "Ideal School",
    "address": "Building 12, Street 340, Al Sadd, Doha", "billing_address": "Building 12, Street 340, Al Sadd, Doha",
    "shipping_address": "Building 12, Street 340, Al Sadd, Doha", "city": "Doha", "country": "Qatar", "area": "Al Sadd",
    "current_location": "Kerala, India", "work_location": "Doha, Qatar", "countries": "Qatar, UAE, Saudi Arabia",
    "nationality": "Indian", "languages": "English, Hindi, Malayalam", "education": "B.Com", "trade": "Electrician",
    "position": "Sales executive", "designation": "Sales executive", "job_title": "Sales executive", "role_title": "Cashier",
    "department": "Sales", "specialty": "Electrical", "source": "Instagram",
    # ids & documents
    "vat_number": "300123456700003", "tax_number": "300123456700003", "trn": "300123456700003", "registration": "300123456700003",
    "registration_number": "CR 123456", "cr_number": "CR 123456", "licence": "MOL-12345",
    "passport_number": "N1234567", "passport_no": "N1234567", "qid": "28435612345", "document_number": "N1234567",
    "document_type": "Passport", "identifier": "MRN-10023", "reference_code": "REF-001",
    # web
    "website": "https://www.example.com", "url": "https://www.example.com", "map_url": "https://maps.app.goo.gl/…",
    "instagram": "@yourbusiness", "facebook": "yourbusiness", "tiktok": "@yourbusiness",
    # money & documents
    "bank_name": "QNB", "iban": "QA58 DOHB 0000 1234 5678 90AB CDEF G", "account_number": "0123456789",
    "swift": "QNBAQAQA", "cheque_number": "000123", "reference": "INV-2026-0001", "invoice_number": "INV-2026-0001",
    "bill_number": "BILL-1045", "asset_code": "FA-0001", "code": "EID20", "batch_number": "B2026-001",
    # notes
    "notes": "Any extra details", "note": "Any extra details", "memo": "Any extra details", "remarks": "Any extra details",
    "reason": "Family function", "description": "Short description", "last4": "1234",
    "attributes_text": "Material: Cotton\nOrigin: Turkey", "title": "Follow-up visit", "case_type": "Consultation", "benefits": "Food, accommodation, transport",
    "details": "King bed, sea view, 2 guests", "schedule": "Sun & Tue 4–6 pm", "device_description": "iPhone 13, cracked screen",
    "cycle_description": "Giant Talon 29, black", "opening_hours": "Sat–Thu 10am–11pm\nFri 1pm–11pm",
    # products & industry details
    "barcode": "6281000000017", "model_number": "SM-A155F", "serial_number": "R58N12ABCDE", "imei": "356789012345678",
    "size": "M / 42 / 500 ml", "colour": "Black", "color": "Black", "material": "Cotton", "design": "Round neck",
    "flavour": "Chocolate", "manufacturer": "GSK", "make": "Toyota", "model": "Land Cruiser", "garment_type": "Kandura",
    "author": "Paulo Coelho", "isbn": "9780062315007", "publisher": "HarperCollins", "grade_subject": "Grade 5 – Maths",
    "hs_code": "8517.13", "country_of_origin": "China", "dimensions": "30 × 20 × 10 cm", "vin": "JTMHV05J604123456",
    "chassis_number": "JTMHV05J604123456", "transmission": "Automatic", "movement": "Automatic", "strap_material": "Leather",
    "water_resistance": "100 m", "fragrance_family": "Oud / woody", "concentration": "Eau de Parfum", "gender": "Men",
    "size_range": "S–XXL", "colour_range": "Black, white, navy", "material_spec": "100% cotton", "design_reference": "DS-2026-01",
    "season_collection": "Summer 2026", "age_group": "3–5 years", "allergens": "Contains nuts", "skin_type": "All skin types",
    "shade": "Nude beige", "part_number": "04465-0K240", "oem_number": "04465-0K240", "compatible_models": "Toyota Hilux 2016–2023",
    "lens_type": "Single vision", "frame_material": "Titanium", "pet_type": "Cat", "flower_type": "Red roses",
    "occasion": "Anniversary", "instrument_type": "Acoustic guitar", "fuel_grade": "Super 95", "tank_number": "Tank 2",
    "paper_size": "A4", "print_type": "Offset", "power_range": "-6.00 to +4.00", "quality_standard": "ISO 9001",
    "safety_standard": "CE", "certification": "Halal", "application_details": "Interior walls", "unit_density": "1.2 kg/L",
    "pack_size": "6 × 1 L", "carton_reference": "CT-24", "bom_reference": "BOM-001", "supplier_code": "SUP-001",
    "marketplace_sku": "AMZ-12345", "scale_code": "21001", "barcode_type": "EAN-13", "brand_code": "SAM",
    "shelf_location": "Aisle 3, shelf B", "product_type": "Finished goods", "battery": "5000 mAh", "ram": "8 GB",
    "storage": "128 GB", "network": "5G", "stone_details": "0.5 ct diamond", "purity": "22K",
    "days_product_expiry": "60, 30, 7", "days_membership_expiry": "7, 3, 1", "days_customer_payment_due": "3, 1",
    "days_supplier_payment_due": "3, 1",
    "model_year": "2024", "plate_number": "123456", "vehicle_number": "123456", "room_number": "101", "table_number": "T1", "category": "Vehicles",
}

NUMBER_SAMPLES = {
    "selling_price": "25.00", "price": "25.00", "cost_price": "15.00", "unit_price": "25.00", "unit_cost": "12.50",
    "purchase_price": "450.00", "wholesale_price": "20.00", "rate": "150.00", "fee": "500.00", "amount": "100.00",
    "cost": "3500.00", "salary": "4500.00", "basic_salary": "4500.00", "expected_salary": "2500", "allowance": "800.00",
    "deduction": "0", "monthly_deduction": "500.00", "overtime_rate": "15.00", "monthly_rent": "6500.00",
    "accepted_value": "600.00", "quoted_value": "650.00", "making_charge": "120.00", "stone_value": "0",
    "debit": "1000.00", "credit": "1000.00", "opening": "10000.00", "discount_value": "10", "value": "10",
    "max_discount": "50", "usage_limit": "100", "points": "100",
    "reorder_level": "10", "quantity": "1", "qty": "1", "quantity_received": "100", "capacity": "4", "seats": "4",
    "guest_count": "2", "preparation_minutes": "15", "duration_minutes": "30", "duration_days": "30", "session_count": "10",
    "sort_order": "0", "vacancies": "5", "contract_months": "24", "experience_years": "3", "warranty_months": "12",
    "lead_time_days": "7", "production_lead_days": "14", "service_interval_days": "180", "minimum_order_quantity": "10",
    "carton_quantity": "24", "length_per_unit": "50", "width_inches": "58", "chest": "40", "waist": "34", "length": "56",
    "sleeve": "24", "weight_grams": "250", "volume_ml": "100", "gsm": "180", "mileage": "45000", "model_year": "2024",
}
