from engine import *

GS = "getting-started.html"
def gs(anchor, text): return f'<a href="{GS}#{anchor}">{text}</a>'

WALKIN_NOTE = "If the buyer is a passer-by, you do not need to create a customer first — the counter POS uses a built-in <b>Walk-in Customer</b>."

VERTICALS = []

# =============================================================== MOBILE SHOP
VERTICALS.append(dict(
 slug="mobile-shop", name="Mobile Shop", icon="📱", group="Retail & product shops",
 tag="Phones tracked one-by-one by IMEI, plus accessories",
 covers=["Mobile Shop"],
 lead="Track every handset by its IMEI, sell phones with a warranty, and sell chargers, covers and accessories from the same screen — stock and accounts update by themselves.",
 chips=["IMEI tracking","Variants (colour / storage)","Barcode labels","CSV import"],
 menu_title="Mobile Shop",
 menu=["Categories","Products","Units","Brands","Print Barcodes","Phone Units","Sales","Reports"],
 flow=[("Set up brands &amp; categories","one time"),("Add products","phones + accessories"),("Add phone units","one row per IMEI"),("Sell","phone unit or POS"),("Check reports","daily")],
 glance=[("Phones by IMEI","Every handset is a separate unit with IMEI, condition (New / Used / Refurbished) and warranty."),
         ("Accessories &amp; parts","Chargers, covers and cables are normal products sold at the POS with stock counts."),
         ("Variants","Same phone in different colour / storage — each variant has its own SKU and price."),
         ("Instant accounts","Every sale creates an invoice, reduces stock and posts to your books.")],
 setup=[
  ("Add categories and brands",
   ["Open [[[Mobile Shop]]] → [[Categories]] → [[+ Add category]]. Create groups such as <i>Smartphones, Accessories, Chargers, Covers</i>.",
    "Open [[Brands]] → add brands such as <i>Samsung, Apple, Xiaomi, Oppo</i>.",
    "Open [[Units]] → add <b>pcs</b> (pieces). Every product needs a unit."],
   dict(tip="Do this once. Later, when you add 200 products, you will just pick from the drop-downs.")),
  ("Add your products (models and accessories)",
   ["Open [[Products]] → [[+ Add product]].",
    "Fill <b>SKU</b> (your own code, e.g. SAM-A15), <b>Name</b>, <b>Category</b>, <b>Brand</b>, <b>Unit</b>, <b>Cost price</b>, <b>Selling price</b> and <b>Reorder level</b> (the stock number at which you want a low-stock warning).",
    "Use <b>Extra details</b> to add one detail per line, like <code>Storage: 128GB</code> or <code>Colour: Black</code>.",
    "Press Save. You will see <i>“Product added.”</i>"],
   dict(note="For <b>phones</b> you add the model here <u>and</u> then add each physical handset under <b>Phone Units</b> (next step). For <b>accessories</b> you only add the product and buy stock through <b>Purchases</b>.")),
  ("Have many products already? Import them from Excel/CSV",
   ["On [[Products]] press [[Import CSV]].",
    "Your file needs these column headings in the first row: <b>SKU, Name, Unit, Selling Price</b> (required) and optional <b>Category, Brand, Cost Price, Reorder Level</b>.",
    "Upload. New SKUs are created, existing SKUs are updated, and missing categories / brands / units are created automatically."],
   dict(tip="Use [[Export CSV]] first to download your current list — edit it in Excel and import it back to change prices in bulk.")),
 ],
 tasks=[
  ("Add a phone unit (each handset with IMEI)",
   ["Open [[Phone Units]] → [[+ Add unit]].",
    "Choose the <b>Product</b> (model), type the <b>IMEI</b>, optional <b>Serial number</b>, pick <b>Condition</b> (New / Used / Refurbished), <b>Warranty (months)</b> and your <b>Purchase price</b>.",
    "Keep <b>Status</b> as <b>In Stock</b> and save. The phone is now ready to sell."],
   dict(warn="Type the IMEI exactly — it is how you will find this handset later for warranty, returns and repair.")),
  ("Sell a phone",
   ["Open [[Phone Units]] and find the handset (search the IMEI on your screen with Ctrl+F).",
    "Press [[Sell]] on that row.",
    "Choose the <b>Customer</b>, confirm the <b>Sale price</b> and <b>Sold date</b>, then confirm.",
    "You will see <i>“Sold … (IMEI …)”</i>. An invoice is created and the unit moves to <b>Sold</b>."],
   dict(note="Only units with status <b>In Stock</b> can be sold. If you see <i>“This unit isn’t available to sell”</i> the handset is already sold, returned or under repair.")),
  ("Sell accessories quickly at the counter (POS)",
   ["Open [[[Sales]]] → [[POS]].",
    "Search by product name or SKU and click the item to add it to the cart. Change quantity if needed.",
    "Select the <b>Customer</b> (or leave <b>Walk-in Customer</b>), optional <b>Coupon code</b>, choose <b>Cash / Card / Bank Transfer</b>.",
    "Press [[Complete Sale]], then <b>Print receipt</b>."],
   dict(tip=f"Full POS guide: {gs('pos','Getting started → POS')}.")),
  ("Add a variant (colour / storage)",
   ["On [[Products]] find the model and press [[+ Variant]].",
    "Enter the <b>Variant label</b> (for example <i>Black / 128GB</i>), a new <b>SKU</b>, <b>Cost price</b> and <b>Selling price</b>.",
    "The variant appears under the product with its own stock and barcode."]),
  ("Print barcode labels",
   ["Open [[Print Barcodes]], tick the products and enter the number of labels for each.",
    "Press [[Generate labels]] and print. Or open one product and press [[Barcode]]."]),
  ("Record a customer return of a phone",
   ["Open [[[Sales]]] → [[Returns &amp; Refunds]] and enter the invoice number (like <b>INV-000123</b>).",
    "Enter the return quantity, reason and refund method (Cash, Card, Bank or Store Credit). Stock and accounts are corrected automatically."],
   dict(note=f"Full step-by-step: {gs('returns','Getting started → Returns')}.")),
  ("Check what you sold",
   ["Open [[Sales]] (under Mobile Shop) to see every phone sold: date, product, IMEI, customer and price.",
    "Open [[Reports]] for total revenue, units sold, units in stock and top-selling products."]),
 ],
 auto=["Each phone sale creates a numbered invoice and posts to your accounting books.",
       "Stock reduces on every sale; a <b>Low stock</b> alert is raised when an item reaches its reorder level.",
       "Buying stock from a supplier (<b>Purchases</b>) increases stock and records what you owe the supplier."],
 reports=[("Total revenue","Sales value of all phones sold"),("Units sold","Number of handsets sold"),("Units in stock","Handsets still available"),("Top-selling products","Best models by units and revenue")],
 statuses=[("In Stock","ok","Ready to sell"),("Sold","info","Sold to a customer, invoice created"),("Returned","warn","Customer returned it"),("Under Repair","grey","Not available to sell")],
 faq=[("Do I have to add every accessory as a phone unit?","No. Only phones (things you track by IMEI / serial) need units. Accessories are normal products — buy stock and sell them at the POS."),
      ("I sold the wrong price. Can I edit?","Create a return for the invoice and sell again with the right price, so your books stay correct."),
      ("Can two people sell at the same time?","Yes. Give each staff member their own login (see Team &amp; roles in Getting started).")],
))

# =============================================================== GYM
VERTICALS.append(dict(
 slug="gym", name="Gym / Fitness Center", icon="🏋️", group="Fitness & wellness",
 tag="Membership plans, members, daily attendance",
 covers=["Gym / Fitness Center"],
 lead="Sell membership plans, enrol members in a minute, check members in and out every day and see who is active, expired or frozen.",
 chips=["Membership plans","Auto-invoice on enrol","Daily attendance","Member status"],
 menu_title="Gym", menu=["Members","Membership Plans","Attendance","Reports"],
 flow=[("Create plans","Monthly, Quarterly…"),("Add customer","name + phone"),("Enrol member","invoice is created"),("Check in / out","every visit"),("Reports","active vs expired")],
 glance=[("Plans","Any duration and price — Monthly (30 days), Quarterly (90), Yearly (365)…"),
         ("Enrolment = invoice","Enrolling a member automatically raises the invoice."),
         ("Attendance","One-tap check-in and check-out with a log for today."),
         ("Status","See Active, Expired and Frozen members at a glance.")],
 setup=[
  ("Create your membership plans",
   ["Open [[[Gym]]] → [[Membership Plans]] → [[+ Add plan]].",
    "Enter <b>Name</b> (e.g. <i>Monthly</i>), <b>Duration (days)</b> (e.g. 30) and <b>Price</b>.",
    "Repeat for each plan you sell: Monthly, Quarterly, Half-yearly, Yearly, Student, Couple…"],
   dict(tip="You can edit or delete a plan later. A plan that already has members cannot be deleted — deactivate by creating a new plan instead.")),
  ("Add your first customers",
   ["Open [[[People]]] → [[Customers]] → [[+ Add customer]].",
    "Type <b>Name</b> and <b>Phone</b> (email and address are optional). Save."],
   dict(note="A gym member is simply a customer who has been <b>enrolled</b> in a plan.")),
 ],
 tasks=[
  ("Enrol a new member",
   ["Open [[Members]] → [[+ Enroll member]].",
    "Pick the <b>Customer</b> — only customers who are not already members appear in the list.",
    "Pick the <b>Plan</b> and the <b>Join date</b>.",
    "Press Save. You will see <i>“Member enrolled and invoiced.”</i>"],
   dict(warn="If you get <i>“Couldn’t enroll member”</i>, read the reason shown after it — most often the plan or customer is missing.")),
  ("Check members in and out every day",
   ["Open [[Attendance]]. The top table lists your active members.",
    "Press [[Check in]] next to the member when they arrive. The visit appears in <b>Today’s log</b> with the time.",
    "When they leave, press [[Check out]] on their log row."],
   dict(note="You cannot check in someone who is already inside — you will see <i>“… is already checked in.”</i>")),
  ("Find a member and see their plan",
   ["Open [[Members]]. Each row shows the customer, plan, join date and status (Active / Expired / Frozen).",
    "Use your browser search (Ctrl+F) to find a name quickly on long lists."]),
  ("Check gym performance",
   ["Open [[Reports]]: see how many members are <b>Active</b>, <b>Expired</b> and <b>Frozen</b>, and how many members each plan has.",
    "For income and expenses use [[Analytics]] under Business."]),
 ],
 auto=["Enrolling a member creates the sales invoice for that plan automatically.",
       "The member’s status is shown as Active, Expired or Frozen, so you know who needs to renew.",
       "Attendance keeps a dated log of check-in and check-out times."],
 reports=[("Active members","Members whose plan is running"),("Expired","Members whose plan has ended — follow up to renew"),("Frozen","Memberships on hold"),("Members by plan","How many members are on each plan")],
 statuses=[("Active","ok","Can check in"),("Expired","bad","Plan ended"),("Frozen","warn","On hold")],
 faq=[("A customer is missing from the Enroll list.","Either they are not added under Customers yet, or they are already a member (each customer can be a member once)."),
      ("Can I take payment for the plan?","The invoice is created when you enrol. Record how the customer paid using your normal billing/payment flow (POS for counter items; contact support if you need payment posting help)."),
      ("Can trainers have their own login?","Yes — add them under Team &amp; roles with the Staff role.")],
))

# =============================================================== SPA
def appt_business(slug, name, icon, group, tag, covers, who, who_plural, ser_names, lead, extra_faq=None, menu_title=None, form_note=None, chips=None, examples=None, staff_role="Therapist"):
    ex = examples or "Haircut, Hair colour, Facial"
    return dict(
     slug=slug, name=name, icon=icon, group=group, tag=tag, covers=covers, lead=lead,
     chips=chips or ["Appointments","Services &amp; prices","Staff commission","Auto-invoice"],
     menu_title=menu_title or name, menu=["Appointments","Services","Staff","Reports"],
     flow=[("Add services","name, time, price"),("Add staff",who_plural),("Book appointment","invoice is created"),("Mark completed","commission recorded"),("Reports","by service")],
     glance=[("Services","Each service has a name, duration in minutes and price."),
             ("Staff","Add your "+who_plural.lower()+" with role and salary details."),
             ("Bookings","Book a customer with a service, a staff member and a date/time."),
             ("Commission","Enter a commission % on the booking — it is recorded when you complete the appointment.")],
     setup=[
      ("Add your services",
       [f"Open [[[{menu_title or name}]]] → [[Services]] → [[+ Add service]].",
        "Enter <b>Name</b>, <b>Duration (minutes)</b> and <b>Price</b>.",
        f"Repeat for everything you offer, for example: <i>{ex}</i>."],
       dict(tip="Keep names short and clear — they appear on invoices.")),
      (f"Add your staff ({who_plural.lower()})",
       [f"Open [[Staff]] → [[+ Add staff]].",
        f"Enter <b>Name</b>, <b>Phone</b>, <b>Role title</b> (e.g. <i>{staff_role}</i>), <b>Salary</b> and <b>Joined date</b>.",
        "Save. They now appear in the booking form."],
       dict(note="<b>Staff</b> here means people who do the work. Logins for your team are different — see <i>Team &amp; roles</i> in Getting started.")),
      ("Add your customers",
       ["Open [[[People]]] → [[Customers]] → [[+ Add customer]] with name and phone. You can also add them while you book."]),
     ],
     tasks=[
      ("Book an appointment",
       [f"Open [[Appointments]] → [[+ Book appointment]].",
        f"Choose the <b>Customer</b>, the <b>Service</b>, the <b>{who}</b> and the <b>date &amp; time</b>.",
        f"Enter the <b>{who} commission %</b> if you pay commission (leave 0 if not).",
        "Save. You will see the booking with status <b>Booked</b>."],
       dict(note=form_note) if form_note else None),
      ("Complete an appointment after the service",
       ["Open [[Appointments]] and find the booking.",
        "Press [[Complete]]. The status changes to <b>Completed</b> and the staff commission (if any) is recorded."]),
      ("Cancel or mark a no-show",
       ["Open [[Appointments]] → press [[Cancel]] on the booking. It is counted under <b>Cancelled/No-show</b> in your reports."]),
      ("Change a price or add a service later",
       ["Open [[Services]] → press [[Edit]] to change name, duration or price; or [[+ Add service]] for a new one.",
        "Old appointments keep the price they were booked with."],
       dict(warn="A service that already has appointments cannot be deleted — edit it instead.")),
      ("See your day at a glance",
       ["The <b>Overview</b> page shows <b>Appointments today</b> and completed totals.",
        "Open [[Reports]] to see Booked / Completed / Cancelled counts, revenue and revenue by service."]),
     ],
     auto=["Booking creates the invoice for the service price automatically.",
           "Completing the appointment records the staff commission you entered.",
           "Reports summarise bookings and revenue per service without any extra work."],
     reports=[("Booked","Appointments still to be done"),("Completed","Appointments finished"),("Cancelled / No-show","Bookings that did not happen"),("Revenue","Money earned from completed appointments"),("Revenue by service","Which services earn the most")],
     statuses=[("Booked","info","Scheduled"),("Completed","ok","Service done, commission recorded"),("Cancelled","bad","Cancelled or no-show")],
     faq=[("I booked at the wrong time.","Cancel the booking and book a new one at the right time."),
          ("Where do I see staff commission?","It is recorded against the staff member when you press Complete. Your accountant can view it in the accounts."),
          ("The staff drop-down is empty.","Add staff first under <b>Staff</b> → <b>+ Add staff</b>.")]+(extra_faq or []),
    )

VERTICALS.append(appt_business("spa","Spa / Massage Centre","💆","Beauty, salon & spa","Services, therapists, appointments and commission",["Spa / Massage Centre"],"Therapist","Therapists",None,
  "Manage treatments and therapists, book clients, and keep commission and revenue clear for every service.",
  menu_title="Spa", examples="Swedish massage 60 min, Aromatherapy 90 min, Foot reflexology", staff_role="Therapist"))

VERTICALS.append(appt_business("saloon","Saloon / Barber Shop","💈","Beauty, salon & spa","Services, stylists, appointments and commission",["Saloon / Barber Shop"],"Stylist","Stylists",None,
  "Run a busy barber shop or saloon — services, stylists, bookings and commission all in one simple flow.",
  menu_title="Saloon", examples="Haircut, Beard trim, Shave, Hair colour", staff_role="Barber / Stylist"))

VERTICALS.append(appt_business("beauty-parlour","Beauty Parlour / Beauty Salon","💅","Beauty, salon & spa","Services, beauticians, appointments and commission",["Beauty Parlour / Beauty Salon"],"Beautician","Beauticians",None,
  "Manage facials, bridal packages, threading and more — book clients with the right beautician and see revenue by service.",
  menu_title="Beauty Parlour", examples="Facial, Threading, Bridal makeup, Manicure", staff_role="Beautician"))
