"""Business guides added after the first edition: restaurants, bookings, education, property,
jewellery, sell-by-weight shops and recruitment agencies."""
from engine import *
from verticals_a import gs

VERTICALS = []

# ------------------------------------------------------------------ RESTAURANT
VERTICALS.append(dict(
 slug="restaurant", name="Restaurant, Café &amp; Catering", icon="🍽️", group="Restaurants & food",
 tag="Tables, KOT, quick counter sale, website orders and monthly mess",
 covers=["Restaurant / Cafeteria", "Café / Juice Shop", "Catering Company"],
 lead="Take dine-in, takeaway and delivery orders, send them to the kitchen (KOT), bill in seconds, run a fast counter with Quick sale, accept orders from your own website and run monthly mess members — with stock, staff and accounts updated for you.",
 chips=["Tables &amp; KOT", "Quick sale", "Website orders", "Mess (monthly meals)", "Works offline"],
 menu_title="Restaurant / Cafeteria",
 menu=["Restaurant Dashboard", "New Order", "Quick sale", "Orders (bills)", "Online orders", "Kitchen / KOT", "Menu &amp; Ingredients", "Reports"],
 flow=[("Open shift", "count the cash drawer"), ("Take orders", "table, takeaway or delivery"), ("Kitchen cooks", "KOT / kitchen screen"), ("Bill &amp; pay", "cash, card or bank"), ("Close shift", "Z report")],
 glance=[("Order types", "<b>Dine-in</b> at a table, <b>Takeaway</b> and <b>Delivery</b> with address and phone."),
         ("Kitchen (KOT)", "Each order goes to the kitchen as a ticket. Added dishes go as a new <b>round</b>, so the kitchen only sees what is new."),
         ("Quick sale", "A tap-tile counter for tea, juice and snacks — no table, no kitchen, one tap to take cash or card."),
         ("Website orders", "Customers order from your website; you accept and it goes to the kitchen."),
         ("Mess", "Monthly meal members, daily meal tick, mess cut (leave) and one-step monthly bills."),
         ("Offline", "If the internet stops, keep billing. Bills sync by themselves when it comes back.")],
 setup=[
  ("Load your menu",
   ["Open [[Menu &amp; Ingredients]]. Add each dish with [[Add menu item]]: <b>Name</b>, <b>Category</b>, <b>Price</b>, photo, <b>Vegetarian</b>, <b>Spice level</b> and <b>Preparation time</b>.",
    "Kerala restaurant? Press [[Load Kerala menu]] to load a full menu with photos in one step, then change names and prices.",
    "Use <b>Add-ons / extras</b> for things like extra cheese or a bigger size."],
   dict(tip="Sample data (staff and expenses) can be removed any time with [[Remove sample data]].")),
  ("Add dining areas and tables",
   ["Open [[Restaurant Dashboard]] → [[⚙ Restaurant Setup]] → [[＋ Add Area]] (e.g. Ground floor, Family room).",
    "Press [[＋ Add Table]] and enter the table name and number of seats."]),
  ("Set service charge, tax and printers",
   ["In Restaurant Setup set the <b>Service charge %</b> and tax if you charge them.",
    "Open [[[Settings]]] → [[Devices &amp; Printers]] to connect the receipt printer, kitchen printer and cash drawer. See the Devices guide."]),
 ],
 tasks=[
  ("Take a dine-in order",
   ["Press [[＋ New Order]] → <b>Dine-in</b> → choose a free table and enter the number of <b>Guests</b>.",
    "Tap dishes to add them. Add a <b>Kitchen note</b> such as <i>No onion, extra spicy</i>.",
    "Press [[Send to Kitchen]]. The kitchen gets a KOT ticket."],
   dict(tip="To add more dishes later, open the order, add them and press [[Send to Kitchen]] again — only the new dishes print, marked <b>ADD-ON · ROUND 2</b>.")),
  ("Move, split or merge a bill",
   ["Open the order → [[More options]] → <b>Move table · Guests · Split · Merge</b>.",
    "<b>Move to another table</b>, update the guest count, <b>Split into new order</b> (pick the items) or <b>Merge orders</b> from another table."]),
  ("Take payment and print the bill",
   ["On the order press [[💳 Pay]]. Choose <b>Cash</b>, <b>Card</b> or <b>Bank</b>. For cash, type the amount received to see the change.",
    "For card: enter the amount on the card machine, then confirm. Add the approval code if you want.",
    "Press [[Print Receipt]] or [[Share bill]] on WhatsApp."]),
  ("Sell fast at the counter (Quick sale)",
   ["Open [[Quick sale]]. Tap the tiles (tea, juice, snacks) to add them. Not on the list? Type the name and price on the right.",
    "Press <b>Cash</b> or <b>Card</b> — done. Use [[Edit quick tiles]] to choose your top items."]),
  ("Run the kitchen screen",
   ["Open [[Kitchen / KOT]] on a tablet or TV in the kitchen. Tickets show oldest first.",
    "Press [[Start cooking →]] then [[Mark ready →]]. Waiters see what is ready."]),
  ("Accept website orders",
   ["Open [[🛒 Online orders]]. New orders beep and show a badge in the menu.",
    "Press [[Accept &amp; send to kitchen]] or [[Reject]] with a reason. The customer sees the status on their tracking page.",
    "Switch ordering on in <b>Website ordering settings</b>: pickup, delivery, delivery charge, minimum order and ready time. Use [[Pause orders]] when the kitchen is full."],
   dict(note="See the Website &amp; online orders guide for putting the cart on your website or WordPress.")),
  ("Run the monthly mess",
   ["Open [[[Mess]]] → [[Mess plans]] → [[Create plan]] (e.g. Full mess – 3 meals, monthly fee, mess-cut refund per day).",
    "[[New member]]: choose the customer and plan. Each day open [[Today's meals]] and tick who ate.",
    "Member going on leave? Add a <b>Mess cut</b>. At month end press [[Create all bills]] in [[Monthly bills]]; follow up in [[Mess dues]]."]),
  ("Open and close the shift",
   ["Open [[Restaurant Dashboard]] → [[◷ Shift Control]] → [[Open Shift]] and count the cash drawer.",
    "At closing press [[Close Shift]], count the cash and press [[Print Z Report]]. Any difference is shown as <b>Variance</b>."]),
 ],
 auto=["Every bill creates an invoice, posts to your accounts and reduces ingredient stock if you use recipes.",
       "Added dishes go to the kitchen as a new round — the kitchen never cooks the same dish twice.",
       "Website orders beep in the app; with auto-accept on they go straight to the kitchen.",
       "If the internet stops, the POS keeps working and syncs the bills when it is back.",
       "Mess bills include the mess-cut refund for long leaves automatically."],
 reports=[("Sales today / this month", "Bills, average bill and payment mix"),
          ("Orders (bills)", "Every bill with filters for type, table, customer and date"),
          ("Shifts &amp; Z reports", "Cash expected vs counted for each shift"),
          ("Food waste", "What was thrown away and its cost"),
          ("Mess dues", "Who still has to pay this month")],
 statuses=[("New", "info", "Order taken, not yet sent to kitchen"), ("Preparing", "warn", "Kitchen is cooking"),
           ("Ready", "ok", "Ready to serve or hand over"), ("Paid", "ok", "Bill closed"), ("Cancelled", "bad", "Order cancelled")],
 faq=[("The kitchen printed my add-on dishes again — why?", "It prints only the new round. Older dishes are not printed again. Check the ticket says <b>ADD-ON · ROUND</b>."),
      ("Can I bill without internet?", "Yes. Use [[Offline POS]]. Bills are saved on the device and sync automatically. The invoice number comes after sync."),
      ("Do I need a printer?", "No. You can share the bill on WhatsApp. A printer makes the counter faster."),
      ("Can customers order from my Hostinger / WordPress website?", "Yes — install the BookPilot WordPress plugin and switch on website ordering. See the Website &amp; online orders guide.")],
))

# ------------------------------------------------------------------ BOOKINGS
VERTICALS.append(dict(
 slug="bookings", name="Hotels, Rentals, Halls &amp; Co-working", icon="🛏️", group="Bookings & rentals",
 tag="Rooms, vehicles, equipment, halls and desks booked by date",
 covers=["Hotel / Hotel Apartment", "Car Rental", "Equipment Rental", "Wedding / Party Hall", "Co-working Space"],
 lead="See every room, vehicle, hall or desk on one calendar. Book, take an advance and a security deposit, check in, check out and bill — late returns and extras are added for you.",
 chips=["Booking calendar", "Advance &amp; deposit", "Check-in / check-out", "Online booking"],
 menu_title="Bookings",
 menu=["Booking calendar", "New booking", "All bookings", "Rooms / Vehicles / Halls…"],
 flow=[("Add rooms / vehicles", "with rate"), ("Book", "dates + advance"), ("Check in", "hand over"), ("Check out", "extras + invoice"), ("Return deposit", "when all is fine")],
 glance=[("One calendar", "Each row is a room, vehicle, hall or desk. Tap an empty day to book it."),
         ("Money up front", "Record an <b>advance</b> and a refundable <b>security deposit</b> on the booking."),
         ("Check out &amp; bill", "Adds nights/days used, late return, extras (minibar, fuel, damage) and discount, then creates the invoice."),
         ("Online", "Customers can request a booking from your website; you confirm in the app.")],
 setup=[
  ("Add what you rent out",
   ["Open [[[Bookings]]] → your list (it is named for your business: <b>Rooms</b>, <b>Vehicles</b>, <b>Equipment</b>, <b>Halls</b> or <b>Spaces</b>).",
    "Press [[Add]] and enter the name or number, the <b>rate</b> and the rate unit (per night, day, hour or event)."]),
  ("Switch on online booking (optional)",
   ["Open [[[Online booking]]] → [[Booking settings]]: switch it on and set minimum notice and how many days ahead people can book.",
    "Put the form on your website — see the Website &amp; online orders guide."]),
 ],
 tasks=[
  ("Make a booking",
   ["Open [[Booking calendar]] and tap an empty day on the right row — or press [[＋ New booking]].",
    "Choose the customer (or type a new name and phone), the <b>From</b> and <b>Until</b> dates/times and the number of guests.",
    "Enter the <b>Advance paid now</b> and the <b>Security deposit</b> if you take one. Press [[Book]]."],
   dict(warn="The end must be after the start. A room or vehicle that is already booked for those dates cannot be booked twice.")),
  ("Check in / hand over",
   ["Open the booking and press [[Check in / hand over]]. The calendar shows it as <b>In use</b>."]),
  ("Check out and bill",
   ["Press [[Check out &amp; bill]]. Add extras (minibar, fuel, damage) and any discount.",
    "Press [[Check out &amp; create invoice]]. Late return time is included automatically. The advance is taken off the bill."]),
  ("Return the deposit",
   ["When everything is fine press <b>Deposit returned</b> on the booking."]),
  ("Change dates, cancel or mark no-show",
   ["Open the booking → [[Change dates / move]], [[Cancel booking]] or <b>No-show</b>."]),
  ("Handle online requests",
   ["Open [[[Online booking]]] → [[Booking requests]] → [[Confirm booking]] or [[Decline]]. Then tell the customer on WhatsApp with one tap."]),
 ],
 auto=["Double bookings are blocked.", "Late returns are charged at your rate.", "The advance is deducted from the final invoice and posted to your accounts.",
       "Today's arrivals, check-outs and overdue returns are shown at the top of the calendar."],
 reports=[("Occupancy", "How full you are this month"), ("Arrivals / check-outs today", "Who is coming and leaving"),
          ("Overdue", "Vehicles or equipment not returned on time"), ("All bookings", "Search by customer, number, status and dates")],
 statuses=[("Reserved", "info", "Booked, not yet arrived"), ("Checked in", "ok", "Guest is in / item handed over"),
           ("Checked out", "grey", "Finished and billed"), ("Overdue", "bad", "Should have been returned"), ("Cancelled", "bad", "Booking cancelled")],
 faq=[("My list is called “Vehicles”, the guide says “Rooms”.", "The names follow your business type. The steps are the same."),
      ("Can I take an advance without a deposit?", "Yes. Leave the deposit empty.")],
))

# ------------------------------------------------------------------ EDUCATION
VERTICALS.append(dict(
 slug="education", name="Schools, Tuition, Nurseries &amp; Driving Schools", icon="🎓", group="Education & property",
 tag="Courses or batches, enrolment, monthly fees and attendance",
 covers=["School / Training Institute", "Tuition Center", "Nursery / Daycare", "Driving School"],
 lead="Create courses (or batches, classes or packages), enrol students, mark attendance and bill monthly fees for everyone in one step. See who has not paid.",
 chips=["Courses &amp; batches", "Enrolment", "Monthly fees", "Attendance", "Fees due"],
 menu_title="Courses",
 menu=["Courses / Batches / Classes", "Enrol", "Monthly fees", "Fees due"],
 flow=[("Create course", "fee + schedule"), ("Enrol students", "one minute each"), ("Attendance", "every class"), ("Monthly fees", "one step"), ("Fees due", "follow up")],
 glance=[("Your words", "Tuition centres see <b>Batches</b>, nurseries <b>Classes</b> and <b>Children</b>, driving schools <b>Packages</b> and <b>Learners</b>."),
         ("Monthly fees", "Bill every active student for the month with one button."),
         ("Attendance", "Mark P (present), A (absent), L (late) or H (holiday) per class."),
         ("Fees due", "A list of unpaid fee invoices with WhatsApp reminders.")],
 setup=[
  ("Create your courses",
   ["Open your courses menu (named <b>Courses</b>, <b>Batches</b>, <b>Classes</b> or <b>Packages</b>) → [[Add]].",
    "Enter the name, the <b>monthly fee</b> (or package fee), the teacher and the timings."]),
 ],
 tasks=[
  ("Enrol a student",
   ["Press [[＋ Enrol]]. Choose an existing student or type a new name and phone.",
    "Pick the course and start date and save. The student appears in the course."]),
  ("Mark attendance",
   ["Open the course and choose the day. Mark each student P, A, L or H and save. You will see <i>“Attendance saved for …”</i>."]),
  ("Bill this month's fees",
   ["Open [[Monthly fees]] → choose the month → [[Create the invoices]]. Students already billed are skipped."]),
  ("Collect fees",
   ["Open [[Fees due]] to see who has not paid and press [[Remind]] to send a WhatsApp reminder.", "Take the payment under [[[People]]] → [[Money to collect]]."]),
 ],
 auto=["Fee invoices post to your accounts and appear under Money to collect.", "A student is never billed twice for the same month.",
       "Inactive students are not billed."],
 reports=[("Fees due", "Unpaid fees by student"), ("Attendance", "Present / absent per class and day"), ("Students per course", "Strength of each batch")],
 statuses=[("Active", "ok", "Studying and billed monthly"), ("Withdrawn", "grey", "Left — no more fees are billed")],
 faq=[("Can a student take two courses?", "Yes. Enrol them in each course; each fee is billed separately."),
      ("Where are the menu words changed?", "They follow your business type automatically.")],
))

# ------------------------------------------------------------------ PROPERTY
VERTICALS.append(dict(
 slug="property", name="Property Management &amp; Real Estate", icon="🏢", group="Education & property",
 tag="Buildings, units, leases and monthly rent",
 covers=["Property Management", "Real Estate Brokerage"],
 lead="Keep every building and unit, the tenant contract (lease) for each, and bill the monthly rent for all leases in one step. Track deposits and overdue rent.",
 chips=["Properties &amp; units", "Leases", "Monthly rent run", "Deposits"],
 menu_title="Properties",
 menu=["Properties &amp; units", "Leases", "Monthly rent"],
 flow=[("Add property", "building"), ("Add units", "flat, shop, office"), ("Lease", "tenant + rent"), ("Monthly rent", "one step"), ("Collect", "Money to collect")],
 glance=[("Units", "Each unit shows <b>Vacant</b> or <b>Let</b> and its current tenant."),
         ("Leases", "Tenant, start and end dates, monthly rent and security deposit."),
         ("Rent run", "Bill rent for every active lease for the month with one button."),
         ("Reminders", "Overdue rent appears under Money to collect with WhatsApp reminders.")],
 setup=[
  ("Add your properties and units",
   ["Open [[[Properties]]] → [[Properties &amp; units]] → add the building, then add each unit with its normal rent."]),
 ],
 tasks=[
  ("Create a lease",
   ["Open [[Leases]] → [[New lease]]. Choose the unit, choose or type the tenant, enter start/end dates, monthly rent and deposit. Save."]),
  ("Bill this month's rent",
   ["Open [[Monthly rent]] → choose the month → [[Create the rent invoices]]. Leases already billed are skipped."]),
  ("End a lease",
   ["Open the lease and close it. The unit becomes vacant."]),
 ],
 auto=["Rent invoices post to your accounts.", "A lease is never billed twice for the same month.", "Units become vacant when a lease is closed."],
 reports=[("Occupancy", "Let and vacant units"), ("Overdue rent", "Tenants who have not paid, with [[Remind]]"), ("Leases ending in 60 days", "Renew in time"), ("Collected this month", "Rent received")],
 statuses=[("Active", "ok", "Lease running"), ("Vacant", "warn", "Unit has no tenant"), ("Closed", "grey", "Lease ended")],
 faq=[("Can one tenant rent two units?", "Yes — create one lease per unit.")],
))

# ------------------------------------------------------------------ GOLD
VERTICALS.append(dict(
 slug="jewellery", name="Jewellery Shop (gold rate pricing)", icon="🪙", group="Retail & product shops",
 tag="Price by today's gold rate × weight + making charge",
 covers=["Jewelry Shop"],
 lead="Enter today's gold rate once. Every gold item is priced from its weight, karat and making charge — and the POS uses the new price straight away.",
 chips=["Daily gold rate", "Weight &amp; karat", "Making charge", "Stones"],
 menu_title="Gold", menu=["Gold rates &amp; prices"],
 flow=[("Morning", "enter gold rate"), ("Prices update", "all gold items"), ("Sell", "POS"), ("Reports", "daily")],
 glance=[("Rates", "Today's rate per gram for each karat (24K, 22K, 21K, 18K)."), ("Item price", "Weight × rate + making charge + stones."),
         ("One step", "Saving the rate updates every gold item's price.")],
 setup=[("Add gold details to products", ["Open [[Products]] and on each gold item set <b>Weight</b> (g), <b>Karat</b>, <b>Making</b> charge and <b>Stones</b> value."])],
 tasks=[("Update today's rate", ["Open [[[Gold]]] → [[Gold rates &amp; prices]] and type <b>Today's rate per gram</b> for each karat.", "Press [[Save rates]]. Tick <b>Update the selling price of every item to the new rate</b> to reprice everything at once."])],
 auto=["The POS always uses the latest price."],
 reports=[("Rate history", "Every rate you saved"), ("Items priced by gold rate", "Saved price vs price now")], statuses=[],
 faq=[("Can I price one item by hand?", "Yes — leave its gold details empty and set a normal selling price.")],
))

# ------------------------------------------------------------------ WEIGHT
VERTICALS.append(dict(
 slug="sell-by-weight", name="Supermarkets &amp; Fresh Food (sell by weight)", icon="⚖️", group="Retail & product shops",
 tag="Sell in kg and scan weighing-scale barcodes",
 covers=["Supermarket", "Grocery Store", "Fish / Meat Shop", "Fruits &amp; Vegetables Shop", "Bakery", "Agricultural Supplies Store"],
 lead="Sell fish, meat, vegetables and loose items by weight. Scan the label printed by your weighing scale — the POS reads the item and the weight from the barcode.",
 chips=["Sell in kg", "Scale barcodes", "Up to 3 decimals"],
 menu_title="Sell by weight", menu=["Weighing scale"],
 flow=[("Item code", "on product"), ("Scale prints label", "code + weight"), ("Scan at POS", "auto quantity"), ("Pay", "")],
 glance=[("Weighed items", "Set the unit to kg and quantities can have up to 3 decimals."),
         ("Scale barcodes", "Tell BookPilot your scale's prefix (e.g. 20–22) and code length.")],
 setup=[("Set up the scale", ["Open [[[Sell by weight]]] → [[Weighing scale]]. Enter the <b>Barcode prefixes</b> (e.g. <code>20,21,22</code>), <b>Item code digits</b>, what <b>The label contains</b> (weight or price) and <b>Decimals in the value</b>. Save.", "On each weighed product set the <b>Scale code</b> printed by your scale."],
         dict(warn="Prefix and item code must leave at least 3 digits for the value."))],
 tasks=[("Sell a weighed item", ["On the POS, scan the scale label. The item and weight are filled in. Or type the weight by hand."])],
 auto=["Stock is reduced by the exact weight sold."], reports=[("Sales", "As usual in Analytics")], statuses=[],
 faq=[("My scale prints price, not weight.", "Choose the price option in Weighing scale settings.")],
))

# ------------------------------------------------------------------ RECRUITMENT
VERTICALS.append(dict(
 slug="recruitment", name="Recruitment Agency", icon="🧑‍💼", group="Projects & contracting",
 tag="Clients' job orders, candidates, the placement pipeline and a careers website",
 covers=["Recruitment Agency"],
 lead="Take job orders from employers, add candidates with CV and passport details, move them through interview, medical, visa and ticket to joining — then bill the client and track your profit per job. Publish open jobs on your own careers website.",
 chips=["Job orders", "Candidates &amp; CVs", "Pipeline to joining", "Careers website", "Fees &amp; profit"],
 menu_title="Recruitment",
 menu=["Overview", "Clients", "Job orders", "Candidates", "Careers website"],
 flow=[("Client", "employer"), ("Job order", "position + people needed"), ("Candidates", "CV + passport"), ("Pipeline", "interview → visa → ticket"), ("Bill", "fee + costs = profit")],
 glance=[("Pipeline", "CV sent → Shortlisted → Interview → Selected → Medical → Visa → Ticket → Joined."),
         ("Alerts", "Passports expiring in 6 months, visas expiring before travel, interviews in the next 7 days."),
         ("Careers website", "Open jobs on your own website; online applications come straight in."),
         ("Profit", "Client fee, candidate fee and your costs (medical, visa, ticket, agent) per job.")],
 setup=[
  ("Add a client and a job order",
   ["Open [[Clients]] → [[Add a client (employer)]] → save &amp; add a job order: position, number of people, salary, contract and <b>our fee per person</b>."]),
  ("Set up the careers website",
   ["Open [[Careers website]]: choose the web address name, colour, headline and services. Switch <b>Website is live</b> on."]),
 ],
 tasks=[
  ("Add a candidate",
   ["Open [[Candidates]] → [[New candidate]]: name, phone/WhatsApp, passport number and expiry, position/skill, experience and CV."]),
  ("Put candidates forward for a job",
   ["Open the job order → <b>Add candidates to this job</b> — matching available candidates are suggested."]),
  ("Move a candidate through the stages",
   ["On the job, change the <b>Stage</b>. Use <b>Send interview details</b>, <b>Tell candidate: selected</b> and <b>Send travel date</b> to message them on WhatsApp."]),
  ("Bill and see profit",
   ["When people join press [[Bill the client]] (and <b>Bill candidate</b> if you charge a processing fee). Add costs with [[Add cost]]. <b>Fees &amp; profit</b> shows the result."]),
 ],
 auto=["Applications from your website create candidates automatically.", "Expiring passports and visas are listed on the Overview.",
       "Invoices and costs post to your accounts."],
 reports=[("Overview", "Open job orders, people still needed, interviews, joined this month, fees billed"), ("Fees &amp; profit", "Per job order")],
 statuses=[("Selected", "ok", "Client selected the candidate"), ("Joined / deployed", "ok", "Started work — ready to bill"),
           ("Not suitable", "bad", "Rejected"), ("Withdrawn", "grey", "Candidate withdrew")],
 faq=[("The client's name is on the website?", "No. Job seekers never see the client's name."),
      ("Can my existing website show the jobs?", "Yes — use the WordPress plugin or the job-list link on the Careers website page.")],
))
