from engine import *
from verticals_a import gs, GS
VERTICALS = []

# =============================================================== TEXTILE
VERTICALS.append(dict(
 slug="textile", name="Textile &amp; Tailoring Shop", icon="🧵", group="Retail & product shops",
 tag="Fabrics, measurements and tailoring orders",
 covers=["Textile","Tailoring Shop"],
 lead="Sell fabrics by type, colour and design, keep customer measurements, and track every tailoring order from booking to delivery.",
 chips=["Fabric catalogue","Customer measurements","Tailoring orders","Ready → Delivered"],
 menu_title="Textile",
 menu=["Orders","Fabrics","Products (other items)","Categories","Units","Brands","Print Barcodes","Measurements","Reports"],
 flow=[("Add fabrics","type, colour, design"),("Save measurements","per garment"),("New order","invoice is created"),("Mark ready","customer is called"),("Mark delivered","order closed")],
 glance=[("Fabrics","Saree, Dress Material, Shirting, Suiting or Other — with colour, design, material, length and width."),
         ("Measurements","Chest, waist, sleeve, length and notes saved per customer and garment."),
         ("Tailoring orders","Price, order date, promised delivery date, linked measurement and fabric."),
         ("Ready / Delivered","Know which orders are ready for pickup and which are pending.")],
 setup=[
  ("Add units and categories",
   ["Open [[Units]] and add <b>meter</b>, <b>pcs</b>, <b>set</b> (whatever you sell in).",
    "Open [[Categories]] and add groups such as <i>Silk, Cotton, Suiting, Readymade</i>."]),
  ("Add fabrics to your catalogue",
   ["Open [[Fabrics]] → [[+ Add fabric]].",
    "Fill <b>SKU</b>, <b>Name</b>, <b>Category</b>, <b>Unit</b>, <b>Cost price</b> and <b>Selling price</b>.",
    "Choose <b>Fabric type</b> (Saree, Dress Material, Shirting, Suiting, Other), then <b>Colour</b>, <b>Design</b>, <b>Material</b> (cotton, silk…), <b>Length per unit (m)</b> and <b>Width (inches)</b>.",
    "Save. Buy stock through <b>Purchases</b> so the fabric shows an available quantity."],
   dict(tip="Other items like buttons, lining or readymade garments go in [[Products (other items)]].")),
 ],
 tasks=[
  ("Save a customer’s measurements",
   ["Open [[Measurements]] → [[+ Add measurement]].",
    "Pick the <b>Customer</b>, type the <b>Garment type</b> (shirt, pant, blouse, kurta…), then <b>Chest, Waist, Sleeve, Length</b> as needed.",
    "Set <b>Taken on</b> date and add any <b>Notes</b> (fit preferences, style).",
    "Save. You can edit or reuse it for later orders."],
   dict(note="A measurement that is linked to an order cannot be deleted.")),
  ("Create a tailoring order",
   ["Open [[Orders]] → [[+ New order]].",
    "Choose the <b>Customer</b>. Optionally choose the saved <b>Measurement</b> and the <b>Fabric</b> if the shop provides it.",
    "Enter <b>Order date</b>, <b>Expected delivery date</b> and the <b>Price</b>. Add notes if needed.",
    "Save. You will see <i>“Order created.”</i> and the invoice is created automatically."]),
  ("Move an order to Ready, then Delivered",
   ["Open [[Orders]]. New orders show status <b>Pending</b>.",
    "When stitching is finished press [[Mark ready]] — this is your signal to call the customer.",
    "When the customer collects it press [[Mark delivered]]."],
   dict(tip="Keep the <b>Expected delivery date</b> honest — the list shows the due date beside each order so you can spot delays.")),
  ("Edit or cancel an order",
   ["Press [[Edit]] to change price, dates or notes, or [[Cancel]] to cancel the order."]),
  ("Sell cloth by the meter at the counter",
   ["Use [[[Sales]]] → [[POS]]. Search the fabric name or SKU, set the quantity (meters) and complete the sale."]),
  ("Import or export your catalogue",
   ["Open [[Products (other items)]] → [[Import CSV]] / [[Export CSV]] (columns: SKU, Name, Unit, Selling Price, optional Category, Brand, Cost Price, Reorder Level)."]),
 ],
 auto=["A tailoring order raises its own invoice when it is created.",
       "Fabric sales at the POS reduce stock automatically and post to your books.",
       "The dashboard shows <b>Orders pending</b> and <b>Ready for pickup</b> counts."],
 reports=[("Pending","Orders not yet ready"),("In progress","Orders being stitched"),("Ready","Waiting for the customer"),("Delivered","Completed orders"),("Revenue (delivered orders)","Money from delivered orders")],
 statuses=[("Pending","warn","Order taken"),("Ready","info","Ready for pickup"),("Delivered","ok","Handed to customer"),("Cancelled","bad","Order cancelled")],
 faq=[("Can I reuse a customer’s measurement?","Yes — pick the saved measurement in the order form. Edit it if the customer’s size has changed."),
      ("The fabric is not in the order drop-down.","Only add a fabric to an order when your shop provides it. Make sure it exists under Fabrics / Products first."),
      ("How do I know which orders are late?","Open Orders and check the <b>Due</b> date against today.")],
))

# =============================================================== VEHICLE WASH
VERTICALS.append(dict(
 slug="vehicle-wash", name="Vehicle Wash / Car Wash", icon="🚗", group="Auto & service",
 tag="Vehicles, wash packages and wash orders",
 covers=["Vehicle Wash / Car Wash"],
 lead="Register vehicles, price wash packages by vehicle type, run each wash from Booked to Completed, and see revenue by package.",
 chips=["Vehicle register","Packages by vehicle type","Start → Complete","Auto-invoice"],
 menu_title="Vehicle Wash", menu=["Orders","Vehicles","Packages","Reports"],
 flow=[("Create packages","price + time"),("Register vehicle","plate number"),("Book wash","or walk-in"),("Start → Complete","invoice on complete"),("Reports","revenue by package")],
 glance=[("Packages","Basic wash, Full wash, Interior detailing — each priced for Car, SUV, Truck, Bike or Other."),
         ("Vehicles","Plate number, type, make, model and colour linked to the owner."),
         ("Wash orders","Book, start, complete or cancel each wash."),
         ("Invoice on completion","The invoice is raised when you press Complete.")],
 setup=[
  ("Create your wash packages",
   ["Open [[[Vehicle Wash]]] → [[Packages]] → [[+ Add package]].",
    "Enter <b>Name</b> (e.g. <i>Full Wash</i>), <b>Vehicle type</b>, <b>Price</b>, <b>Duration (minutes)</b> and a short <b>Description</b>.",
    "Create separate packages for different vehicle types if prices differ (e.g. Car vs SUV)."]),
  ("Register your regular customers’ vehicles",
   ["Open [[Vehicles]] → [[+ Add vehicle]].",
    "Choose the <b>Customer</b> (add them first under People → Customers), then <b>Vehicle number</b> (plate), <b>Type</b> (Car, SUV, Truck, Bike, Other), <b>Make</b>, <b>Model</b>, <b>Color</b>."]),
 ],
 tasks=[
  ("Book a wash",
   ["Open [[Orders]] → [[+ Book wash]].",
    "Select the <b>Vehicle</b> and the <b>Package</b>. <b>Staff</b> is optional.",
    "Choose the <b>Scheduled at</b> date and time. Leave <b>Price</b> blank to use the package price, or type a special price.",
    "Save. You will see <i>“Wash booked.”</i>"]),
  ("Run the wash: Start and Complete",
   ["When the car goes in, press [[Start]] on the order — status becomes <b>In progress</b>.",
    "When finished, press [[Complete]]. The invoice is created now and the order counts in revenue."],
   dict(warn="Remember to press Complete — revenue and the invoice are only recorded at this step.")),
  ("Cancel a wash",
   ["Press [[Cancel]] on a booked order. Cancelled orders do not create an invoice."]),
  ("Add a new vehicle while the customer waits",
   ["Open [[Vehicles]] → [[+ Add vehicle]] → save, then book the wash straight away."]),
  ("Check daily numbers",
   ["The <b>Overview</b> shows <b>Washes today</b> and revenue.",
    "Open [[Reports]] for Booked / In progress / Completed / Cancelled and <b>Revenue by package</b>."]),
 ],
 auto=["Completing a wash creates the sales invoice for the price of that order.",
       "Reports separate booked, in-progress, completed and cancelled washes.",
       "Vehicle records are kept so repeat customers are quick to book."],
 reports=[("Booked","Washes scheduled"),("In progress","Washes running now"),("Completed","Finished washes"),("Cancelled","Cancelled bookings"),("Revenue (completed)","Money from completed washes"),("Revenue by package","Which package sells best")],
 statuses=[("Booked","info","Scheduled"),("In progress","warn","Vehicle is being washed"),("Completed","ok","Done and invoiced"),("Cancelled","bad","Not done")],
 faq=[("Can I sell air fresheners or polish?","Yes — items added as products can be sold at the POS. If you do not see a products menu on your account, message us and we will enable it."),
      ("Wrong package on an order?","Cancel the order and book again with the correct package."),
      ("Do I have to add every vehicle first?","Yes — a wash order is always linked to a vehicle, so register it once and it is there for next time.")],
))

# =============================================================== SPORTS SHOP
VERTICALS.append(dict(
 slug="sports-shop", name="Sports Shop", icon="🏏", group="Retail & product shops",
 tag="Sports goods by sport, size and gender",
 covers=["Sports Shop","Fitness &amp; Sports Store"],
 lead="Keep cricket, football, badminton, running and gym-equipment stock organised with size, gender and material — and sell fast at the POS.",
 chips=["Sport category","Size &amp; gender","Barcode labels","POS"],
 menu_title="Sports Shop", menu=["Products","Units","Brands","Print Barcodes","Categories"],
 flow=[("Add units, brands, categories","one time"),("Add products","sport + size + gender"),("Buy stock","Purchases"),("Sell","POS"),("Analytics","top sellers")],
 glance=[("Sport categories","Cricket, Football, Badminton, Gym Equipment, Running, Other."),
         ("Size &amp; gender","Men, Women, Unisex or Kids, with size and material."),
         ("Barcodes","Print price labels for shelves and scan at the POS."),
         ("Stock alerts","Set a reorder level and get a low-stock alert.")],
 setup=[
  ("Add units, brands and categories",
   ["Open [[Units]] → add <b>pcs</b>, <b>pair</b>, <b>set</b>.",
    "Open [[Brands]] → add brands such as <i>Nike, Adidas, SG, Yonex</i>.",
    "Open [[Categories]] → add shop sections such as <i>Footwear, Apparel, Equipment</i>."]),
 ],
 tasks=[
  ("Add a sports product",
   ["Open [[Products]] → [[+ Add product]].",
    "Fill <b>SKU</b>, <b>Name</b>, <b>Category</b>, <b>Unit</b>, <b>Cost price</b> and <b>Selling price</b>.",
    "Choose <b>Sport category</b>, type the <b>Size</b>, choose <b>Gender</b> (Men, Women, Unisex, Kids) and <b>Material</b>.",
    "Save. You will see <i>“Product added.”</i>"],
   dict(tip="Same shoe in many sizes? Add one product per size (e.g. <i>NIKE-AIR-UK8</i>) so stock per size is correct.")),
  ("Receive stock from a supplier",
   ["Open [[[Purchases]]] → [[Purchases]] → [[+ New purchase]] and pick the supplier, product, quantity and unit cost.",
    "Stock increases straight away."],
   dict(note=f"More on suppliers: {gs('purchases','Getting started → Suppliers &amp; purchases')}.")),
  ("Sell at the counter",
   ["Open [[[Sales]]] → [[POS]], search by name or SKU (or use the barcode), set quantity, choose payment method and press [[Complete Sale]]."]),
  ("Print barcode labels",
   ["Open [[Print Barcodes]], choose products and number of labels, then [[Generate labels]]."]),
  ("Handle a return or exchange",
   ["Open [[Returns &amp; Refunds]], enter the invoice number, select what is returned and choose how to refund."]),
 ],
 auto=["Every POS sale creates an invoice, reduces stock and updates your books.",
       "Low stock alerts appear on the dashboard and in Notifications.",
       "Analytics show sales by day, payment methods and top-selling products."],
 reports=[("Analytics → Sales","Total sales for the period"),("Analytics → Top-selling products","Which items move fastest"),("Stock by branch","How much stock each branch holds")],
 statuses=[],
 faq=[("Where do I see sales reports?","Open <b>Business → Analytics</b> for sales, expenses, profit, payment methods and top products."),
      ("Can I run more than one shop branch?","Yes — see Branches in Getting started.")],
))

# =============================================================== CYCLE SHOP
VERTICALS.append(dict(
 slug="cycle-shop", name="Cycle Shop", icon="🚲", group="Retail & product shops",
 tag="Cycles by serial number, spares and service tickets",
 covers=["Cycle Shop"],
 lead="Track every cycle by serial number and warranty, sell spares and accessories, and manage repair jobs with service tickets.",
 chips=["Serial numbers","Warranty months","Service tickets","Spares at POS"],
 menu_title="Cycle Shop", menu=["Cycle Units","Products","Categories","Units","Brands","Print Barcodes","Service Tickets","Reports"],
 flow=[("Add products","models + spares"),("Add cycle units","one per serial"),("Sell","cycle or POS"),("Service ticket","repair jobs"),("Reports","stock &amp; tickets")],
 glance=[("Cycle units","Each cycle has a serial number, warranty and purchase price."),
         ("Sell a cycle","Sell to a customer with sale price and date."),
         ("Service tickets","Received → In progress → Completed → Delivered."),
         ("Spares","Tyres, tubes, chains and locks are normal products.")],
 setup=[
  ("Add brands, categories and products",
   ["Open [[Brands]] (e.g. <i>Hero, Hercules, Giant</i>), [[Categories]] (Cycles, Spares, Accessories) and [[Units]] (pcs).",
    "Open [[Products]] → [[+ Add product]] for each cycle model and spare part."]),
 ],
 tasks=[
  ("Add a cycle unit (each physical cycle)",
   ["Open [[Cycle Units]] → [[+ Add unit]].",
    "Choose the <b>Product</b> (model), type the <b>Serial number</b>, <b>Warranty (months)</b> and <b>Purchase price</b>. Keep status <b>In Stock</b>."]),
  ("Sell a cycle",
   ["On [[Cycle Units]] press [[Sell]] next to the cycle.",
    "Choose the <b>Customer</b>, <b>Sale price</b> and <b>Sold date</b>. You will see <i>“Sold … (#serial)”</i>."],
   dict(note="Only <b>In Stock</b> cycles can be sold.")),
  ("Open a service ticket",
   ["Open [[Service Tickets]] → [[+ New ticket]].",
    "Choose the <b>Customer</b>. If the cycle was bought from you pick it in <b>Cycle</b>; otherwise type a <b>Cycle description</b>.",
    "Describe the <b>Issue</b>, optionally choose <b>Staff</b>, and set <b>Received date</b>. Save."]),
  ("Move the ticket along",
   ["Press [[Start]] when work begins (status <b>In progress</b>).",
    "Press [[Complete]] when the repair is done.",
    "Press [[Deliver]] when the customer collects the cycle."],
   dict(note="Tickets track the <b>status</b> of each job. Charge for parts and labour by adding a service item as a product and selling it through the POS.")),
  ("Sell spares and accessories",
   ["Use [[[Sales]]] → [[POS]] — search the item, add it to the cart and complete the sale."]),
  ("Check your numbers",
   ["Open [[Reports]] to see cycles <b>In stock</b>, <b>Sold</b>, <b>Revenue</b> and <b>Open tickets</b>."]),
 ],
 auto=["Selling a cycle creates an invoice and marks the unit as Sold.",
       "Spare-part sales reduce stock and post to your books automatically.",
       "The dashboard shows how many tickets are still open."],
 reports=[("In stock","Cycles you can sell now"),("Sold","Cycles sold"),("Revenue","Money earned from cycle sales"),("Open tickets","Repairs not yet delivered")],
 statuses=[("In Stock","ok","Ready to sell"),("Sold","info","Sold to a customer"),("Returned","warn","Returned by customer"),("Received","warn","Ticket opened"),("In Progress","info","Being repaired"),("Completed","ok","Repair done"),("Delivered","grey","Given back to customer")],
 faq=[("Can I edit a cycle’s details?","Yes — press Edit on the Cycle Units page. A unit with service tickets cannot be deleted."),
      ("Can I open a ticket for a cycle I did not sell?","Yes. Leave the cycle empty and type a description like “Blue Hero 26-inch”.")],
))

# =============================================================== MEDICAL SHOP
VERTICALS.append(dict(
 slug="medical-shop", name="Medical Shop / Pharmacy", icon="💊", group="Retail & product shops",
 tag="Batches, expiry dates and dispensing",
 covers=["Medical Shop / Pharmacy"],
 lead="Receive medicines by batch with expiry dates, dispense with an optional prescription reference, and get warnings before stock expires.",
 chips=["Batch &amp; expiry","Prescription reference","Expiry alerts","Dispense history"],
 menu_title="Medical Shop", menu=["Categories","Products","Units","Brands","Print Barcodes","Batches","Dispense History","Reports"],
 flow=[("Add product","medicine name"),("Add batch","batch no + expiry"),("Dispense","from the batch"),("Watch expiry","alerts 90/30/7 days"),("Reports","expiring &amp; expired")],
 glance=[("Batch tracking","Every delivery is a batch with its own number, expiry, cost and selling price."),
         ("Dispense from a batch","Choose quantity, price and optional prescription reference."),
         ("Expiry alerts","Warnings at 90, 30 and 7 days before expiry."),
         ("History","Every dispense is listed with date, quantity, price and customer.")],
 setup=[
  ("Add categories, brands and units",
   ["Open [[Categories]] (Tablets, Syrups, Injections, Baby care…), [[Brands]] (manufacturers) and [[Units]] (strip, bottle, box, pcs)."]),
  ("Add each medicine as a product",
   ["Open [[Products]] → [[+ Add product]]. Fill SKU, Name (with strength, e.g. <i>Paracetamol 500mg</i>), Category, Brand, Unit, prices and <b>Reorder level</b>."],
   dict(note="The product is the medicine itself. The stock you actually hold is added as <b>batches</b> below.")),
 ],
 tasks=[
  ("Receive stock: add a batch",
   ["Open [[Batches]] → [[+ Add batch]].",
    "Choose the <b>Product</b>, type the <b>Batch number</b> and <b>Manufacturer</b>.",
    "Enter <b>Expiry date</b>, <b>Received date</b>, <b>Purchase price</b>, <b>Selling price</b> and <b>Quantity received</b>.",
    "Save. You will see <i>“Batch added.”</i>"],
   dict(warn="Check the expiry date twice — alerts and reports depend on it.")),
  ("Dispense a medicine",
   ["Open [[Batches]] and press [[Dispense]] on the correct batch.",
    "Enter the <b>Quantity</b>, <b>Sold price</b> and <b>Sold date</b>. Choose a <b>Customer</b> if you want to record one and add a <b>Prescription reference</b> when needed.",
    "Save. You will see <i>“Dispensed.”</i> Stock in that batch reduces."],
   dict(tip="Sell the batch that expires first (first-expiry-first-out).", note="The system stops you if the quantity is more than the batch holds, or if the batch is already expired — you will see a clear message on screen.")),
  ("See what you have dispensed",
   ["Open [[Dispense History]] for the list of date, product, quantity, price and customer (blank customer shows as Walk-in)."]),
  ("Act on expiry alerts",
   ["Open [[Notifications]] (Settings) — you will get alerts at 90, 30 and 7 days before a batch expires.",
    "Open [[Reports]] to see <b>Expiring in 30 days</b> and <b>Already expired</b>, then return or remove those items."],
   dict(warn="Never dispense expired stock. The system will refuse an expired batch — remove it from the shelf or return it to the supplier.")),
  ("Sell non-medicine items (baby food, devices)",
   ["Use the [[POS]] for general items with normal stock instead of batches."]),
 ],
 auto=["Dispensing creates an invoice and reduces the batch quantity.",
       "Expiry checks run automatically and raise notifications at 90, 30 and 7 days.",
       "Reports count batches in stock, expiring soon and already expired."],
 reports=[("Revenue","Money from dispensing"),("Batches in stock","Batches that still have quantity"),("Expiring in 30 days","Sell or return these first"),("Already expired","Remove from shelves")],
 statuses=[],
 faq=[("I received the same medicine with a new batch number.","Add a new batch — each batch keeps its own expiry, price and quantity."),
      ("Can I record the doctor’s prescription number?","Yes — use <b>Prescription reference</b> when dispensing.")],
))

# =============================================================== PROTEIN SHOP
VERTICALS.append(dict(
 slug="protein-shop", name="Protein &amp; Supplements Shop", icon="🥤", group="Retail & product shops",
 tag="Batches with flavour, pack size and expiry",
 covers=["Protein &amp; Supplements Shop"],
 lead="Manage supplements by batch — flavour, pack size and expiry — sell from the right batch and stay ahead of expiry dates.",
 chips=["Flavour &amp; pack size","Expiry alerts","Batch selling","Sale history"],
 menu_title="Protein Shop", menu=["Categories","Products","Units","Brands","Print Barcodes","Batches","Sale History","Reports"],
 flow=[("Add products","whey, creatine…"),("Add batch","flavour, size, expiry"),("Sell","from a batch"),("Watch expiry","alerts"),("Reports","revenue &amp; expiry")],
 glance=[("Batches","Batch number, flavour, pack size (grams), expiry and prices."),
         ("Sell from a batch","Pick the batch, quantity and price."),
         ("Expiry alerts","Warnings at 90, 30 and 7 days."),
         ("Sale history","Date, product, quantity, price and customer.")],
 setup=[
  ("Add categories, brands and products",
   ["Open [[Categories]] (Whey, Mass gainer, Creatine, Vitamins), [[Brands]] and [[Units]] (tub, pack, pcs).",
    "Open [[Products]] → [[+ Add product]] for each supplement (name, SKU, prices, reorder level)."]),
 ],
 tasks=[
  ("Add a new batch when stock arrives",
   ["Open [[Batches]] → [[+ Add batch]].",
    "Select the <b>Product</b>, then <b>Batch number</b>, <b>Flavour</b>, <b>Pack size (grams)</b>, <b>Expiry date</b>, <b>Received date</b>, <b>Purchase price</b>, <b>Selling price</b> and <b>Quantity received</b>.",
    "Save. You will see <i>“Batch added.”</i>"]),
  ("Sell from a batch",
   ["On [[Batches]] press [[Sell]] on the batch.",
    "Enter <b>Quantity</b>, <b>Sold price</b>, <b>Sold date</b> and optionally a <b>Customer</b>.",
    "Save. You will see <i>“Sold.”</i> — the invoice is created and the batch quantity drops."],
   dict(tip="Different flavours or sizes are different batches — pick the right one so stock stays accurate.")),
  ("Review your sales",
   ["Open [[Sale History]] to see every sale with date, product, quantity, price and customer."]),
  ("Handle expiry",
   ["Watch [[Notifications]] for alerts at 90, 30 and 7 days.",
    "Open [[Reports]] → <b>Expiring in 30 days</b> and <b>Already expired</b>, then run a discount offer or remove stock."],
   dict(warn="Remove expired tubs from the shelf — reports will keep listing them until you clear them.")),
 ],
 auto=["Every batch sale creates an invoice and reduces that batch’s quantity.",
       "Daily expiry checks send notifications at 90, 30 and 7 days.",
       "Reports show revenue, batches in stock, expiring soon and already expired."],
 reports=[("Revenue","Money from supplement sales"),("Batches in stock","Batches with quantity left"),("Expiring in 30 days","Sell first / offer discounts"),("Already expired","Remove from sale")],
 statuses=[],
 faq=[("Same product, new flavour?","Add a new batch and type the flavour — the product can stay the same."),
      ("Can I use coupons?","Coupons work on POS sales. See Coupons &amp; loyalty in Getting started.")],
))

# =============================================================== CONSTRUCTION
VERTICALS.append(dict(
 slug="construction", name="Construction / Contracting Company", icon="🏗️", group="Projects & agencies",
 tag="Projects, contractors, expenses and project profit",
 covers=["Construction / Contracting Company"],
 lead="Create projects with a budget and contract value, add contractors, record every expense against a project and see budget remaining and profit at any moment.",
 chips=["Projects","Contractors","Expense by category","Budget vs spent"],
 menu_title="Construction", menu=["Projects","Contractors","Reports"],
 flow=[("Add contractors","subcontractors"),("Create project","budget + contract value"),("Record expenses","material, labour…"),("Open project","budget vs spent"),("Reports","by status")],
 glance=[("Projects","Client, site, dates, budget, contract value and status."),
         ("Contractors","Name, phone and specialty (plumber, electrician…)."),
         ("Project expenses","Material, Labour, Contractor, Equipment or Other — Cash or Bank."),
         ("Project profit","Budget, Spent, Budget remaining and Project profit on every project.")],
 setup=[
  ("Add your contractors and suppliers of labour",
   ["Open [[[Construction]]] → [[Contractors]] → [[+ Add contractor]].",
    "Enter <b>Name</b>, <b>Phone</b> and <b>Specialty</b> (e.g. <i>Electrical</i>). Save."]),
  ("Add your client as a customer",
   ["Open [[[People]]] → [[Customers]] → [[+ Add customer]] for each client so you can link them to projects."]),
 ],
 tasks=[
  ("Create a project",
   ["Open [[Projects]] → [[+ New project]].",
    "Enter <b>Name</b>, choose the <b>Client</b>, type the <b>Site address</b>.",
    "Set <b>Start date</b>, <b>End date</b> (optional), <b>Budget</b> (what you plan to spend) and <b>Contract value</b> (what the client pays you).",
    "Choose <b>Status</b>: Planning, Active, On Hold, Completed or Cancelled. Save. You will see <i>“Project created.”</i>"],
   dict(tip="Update the <b>Status</b> as the job moves — Reports count projects by status.")),
  ("Record an expense against a project",
   ["Open the project with [[View]] and press [[+ Record expense]].",
    "Choose the <b>Project</b> and <b>Category</b> (Material, Labour, Contractor, Equipment, Other).",
    "Choose the <b>Contractor</b> if it was paid to one, then <b>Amount</b>, <b>Date</b>, <b>Description</b> and <b>Payment method</b> (Cash / Bank).",
    "Save. You will see <i>“Expense recorded.”</i>"]),
  ("See how a project is doing",
   ["Open [[Projects]] → [[View]] on a project.",
    "You will see <b>Budget</b>, <b>Spent</b>, <b>Budget remaining</b>, <b>Project profit</b> and the list of expenses with date, category, contractor, amount and description."],
   dict(note="<b>Project profit</b> is your contract value minus what you have spent so far.")),
  ("Edit a project or contractor",
   ["Use [[Edit]] on the project or contractor row. A contractor with recorded expenses cannot be deleted."]),
  ("Company-wide expenses (rent, salaries, fuel)",
   ["Open [[[Finance]]] → [[Expenses]] → [[+ Add expense]] for costs that are not tied to one project. See Getting started → Expenses."]),
  ("Check all projects at once",
   ["Open [[Reports]] to see the number of projects in <b>Planning</b>, <b>Active</b>, <b>Completed</b> and the <b>Total contract value</b>."]),
 ],
 auto=["Every project expense is posted to your accounting books automatically.",
       "The project page recalculates budget remaining and profit each time you add an expense.",
       "The Overview shows <b>Active projects</b> and <b>Total projects</b>."],
 reports=[("Planning","Projects not yet started"),("Active","Projects in progress"),("Completed","Finished projects"),("Total contract value","Sum of all contract values")],
 statuses=[("Planning","grey","Not started"),("Active","ok","In progress"),("On Hold","warn","Paused"),("Completed","info","Finished"),("Cancelled","bad","Stopped")],
 faq=[("What is the difference between Budget and Contract value?","Budget is what you expect to <i>spend</i>; Contract value is what the client <i>pays you</i>."),
      ("Can I record money received from the client?","Client invoices and payments go through Sales / billing. Ask us if you need help setting up stage billing.")],
))
