# Generated by Django 5.1.4 on 2026-09-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('sales', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_type', models.CharField(choices=[('saree', 'Saree'), ('dress_material', 'Dress Material'), ('shirting', 'Shirting'), ('suiting', 'Suiting'), ('other', 'Other')], default='other', max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('design', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('length_per_unit', models.DecimalField(blank=True, decimal_places=2, help_text='Meters per unit sold, if sold by piece rather than by meter.', max_digits=8, null=True)),
                ('width_inches', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fabric_detail', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment_type', models.CharField(max_length=50)),
                ('values', models.JSONField(blank=True, default=dict)),
                ('taken_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TailoringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField()),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready', 'Ready for Pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tailoring_orders', to='customers.customer')),
                ('fabric_product', models.ForeignKey(blank=True, help_text='The fabric product used, if provided by the shop rather than the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product')),
                ('measurement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='textile.measurement')),
                ('sales_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salesinvoice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
