# Generated by Django 5.1.4 on 2026-09-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaservice',
            name='product',
            field=models.OneToOneField(blank=True, help_text="The service Product that book_appointment() invoices a walk-in against — see spa.services.create_spa_service.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spa_service', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='product',
            field=models.OneToOneField(blank=True, help_text="The service Product that purchase_package() invoices against — see spa.services.create_service_package.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spa_service_package', to='inventory.product'),
        ),
    ]
