# Generated by Django 5.1.4 on 2026-09-17 04:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_insert_only_db_grant'),
        ('tenants', '0011_backfill_payroll_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'timestamp'], name='audit_audit_company_80eef3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'model_name', 'object_id'], name='audit_audit_company_a8413e_idx'),
        ),
    ]
