# Generated by Django 5.1.4 on 2026-09-08 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('flavour', models.CharField(blank=True, max_length=100)),
                ('weight_grams', models.PositiveIntegerField(help_text='Pack size, e.g. 1000 for a 1kg tub.')),
                ('expiry_date', models.DateField()),
                ('received_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protein_batches', to='inventory.product')),
            ],
            options={
                'abstract': False,
                'unique_together': {('company', 'product', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='SaleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_date', models.DateField()),
                ('is_returned', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_records', to='protein_shop.proteinbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protein_sales', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
