# Generated by Django 5.1.4 on 2026-09-30 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0003_customer_credit_limit_customer_payment_terms_days"),
        ("inventory", "0008_product_boutique_attributes"),
        ("sales", "0012_offline_sale_sync"),
        ("tenants", "0015_company_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookableResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("room", "Room"),
                            ("vehicle", "Vehicle"),
                            ("equipment", "Equipment"),
                            ("hall", "Hall"),
                            ("space", "Space / desk"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=12,
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rate_unit",
                    models.CharField(
                        choices=[
                            ("hour", "Per hour"),
                            ("day", "Per day"),
                            ("night", "Per night"),
                            ("month", "Per month"),
                            ("event", "Per booking"),
                        ],
                        default="day",
                        max_length=8,
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Guests / seats (0 = not relevant)."
                    ),
                ),
                (
                    "details",
                    models.CharField(
                        blank=True,
                        help_text="e.g. plate number, floor, size, features.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Service product used on invoices; created automatically.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("guests", models.PositiveSmallIntegerField(default=1)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "rate_unit",
                    models.CharField(
                        choices=[
                            ("hour", "Per hour"),
                            ("day", "Per day"),
                            ("night", "Per night"),
                            ("month", "Per month"),
                            ("event", "Per booking"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "advance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Paid in advance; applied to the invoice at check-out.",
                        max_digits=12,
                    ),
                ),
                ("advance_method", models.CharField(default="cash", max_length=10)),
                ("advance_date", models.DateField(blank=True, null=True)),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Refundable; held and returned, not income.",
                        max_digits=12,
                    ),
                ),
                ("deposit_returned", models.BooleanField(default=False)),
                (
                    "extras",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("extras_note", models.CharField(blank=True, max_length=255)),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("checked_in", "Checked in"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No-show"),
                        ],
                        default="reserved",
                        max_length=12,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="customers.customer",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="industry.bookableresource",
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
                "indexes": [
                    models.Index(
                        fields=["company", "resource", "start"],
                        name="industry_bo_company_f0ab91_idx",
                    ),
                    models.Index(
                        fields=["company", "status"],
                        name="industry_bo_company_a50f9d_idx",
                    ),
                ],
            },
        ),
    ]
