# Generated by Django 5.1.4 on 2026-09-30 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0001_bookings"),
        ("tenants", "0015_company_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScaleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "prefixes",
                    models.CharField(
                        default="20,21,22,23,24,25,26,27,28,29",
                        help_text="Barcode prefixes the scale uses, comma separated.",
                        max_length=60,
                    ),
                ),
                (
                    "code_digits",
                    models.PositiveSmallIntegerField(
                        default=5, help_text="Digits of the item code after the prefix."
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[("weight", "Weight (kg)"), ("price", "Price")],
                        default="weight",
                        max_length=8,
                    ),
                ),
                (
                    "value_decimals",
                    models.PositiveSmallIntegerField(
                        default=3, help_text="3 = grams (weight), 2 = cents (price)."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company",), name="one_scale_setting_per_company"
                    )
                ],
            },
        ),
    ]
