# Generated by Django 5.1.4 on 2026-09-30 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_credit_limit_customer_payment_terms_days"),
        ("industry", "0003_education"),
        ("inventory", "0008_product_boutique_attributes"),
        ("sales", "0012_offline_sale_sync"),
        ("tenants", "0015_company_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("building", "Building"),
                            ("villa", "Villa / house"),
                            ("compound", "Compound"),
                            ("commercial", "Commercial"),
                            ("land", "Land / yard"),
                        ],
                        default="building",
                        max_length=12,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        help_text="Landlord, if you manage it for someone else.",
                        max_length=150,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment / flat"),
                            ("villa", "Villa"),
                            ("room", "Room / bed space"),
                            ("shop", "Shop"),
                            ("office", "Office"),
                            ("warehouse", "Warehouse"),
                            ("other", "Other"),
                        ],
                        default="apartment",
                        max_length=10,
                    ),
                ),
                ("bedrooms", models.PositiveSmallIntegerField(default=0)),
                (
                    "size",
                    models.CharField(
                        blank=True, help_text="e.g. 120 m²", max_length=40
                    ),
                ),
                (
                    "monthly_rent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.product",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="industry.property",
                    ),
                ),
            ],
            options={
                "ordering": ["property__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Day of the month rent is due (1–28)."
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("deposit_returned", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("terminated", "Terminated early"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("ended_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="customers.customer",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leases",
                        to="industry.rentalunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="RentCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="industry.lease",
                    ),
                ),
            ],
            options={
                "ordering": ["-period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lease", "period"), name="one_rent_per_lease_month"
                    )
                ],
            },
        ),
    ]
