# Generated by Django 5.1.4 on 2026-09-30 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0004_property"),
        ("tenants", "0015_company_onboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "karat",
                    models.CharField(
                        choices=[
                            ("24K", "24K"),
                            ("22K", "22K"),
                            ("21K", "21K"),
                            ("18K", "18K"),
                        ],
                        max_length=4,
                    ),
                ),
                ("date", models.DateField()),
                ("rate_per_gram", models.DecimalField(decimal_places=2, max_digits=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "karat"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "karat", "date"),
                        name="one_gold_rate_per_karat_day",
                    )
                ],
            },
        ),
    ]
