# Generated by Django 5.1.4 on 2026-10-03 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_credit_limit_customer_payment_terms_days"),
        ("expenses", "0002_budgets"),
        ("industry", "0005_gold_rates"),
        ("sales", "0014_online_payments"),
        ("suppliers", "0002_supplier_payment_terms_days"),
        ("tenants", "0016_membership_branches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20)),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("nationality", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("male", "Male"), ("female", "Female")],
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("passport_no", models.CharField(blank=True, max_length=30)),
                ("passport_expiry", models.DateField(blank=True, null=True)),
                (
                    "trade",
                    models.CharField(
                        blank=True,
                        help_text="Position / skill, e.g. Electrician, Driver, Nurse.",
                        max_length=150,
                    ),
                ),
                (
                    "experience_years",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("gulf_experience", models.BooleanField(default=False)),
                ("current_location", models.CharField(blank=True, max_length=150)),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("languages", models.CharField(blank=True, max_length=150)),
                ("education", models.CharField(blank=True, max_length=150)),
                ("cv", models.FileField(blank=True, upload_to="recruitment/cv/%Y/%m/")),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_process", "In process"),
                            ("placed", "Placed"),
                            ("not_suitable", "Not suitable"),
                        ],
                        default="available",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Sub-agent who sent this candidate.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="candidates",
                        to="suppliers.supplier",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Billing record when the candidate pays a fee.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20)),
                ("position", models.CharField(max_length=150)),
                ("vacancies", models.PositiveIntegerField(default=1)),
                ("work_location", models.CharField(blank=True, max_length=150)),
                (
                    "nationality",
                    models.CharField(
                        blank=True,
                        help_text="Preferred nationality, if any.",
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("male", "Male"),
                            ("female", "Female"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                (
                    "salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "benefits",
                    models.CharField(
                        blank=True,
                        help_text="Accommodation, food, transport…",
                        max_length=255,
                    ),
                ),
                ("requirements", models.TextField(blank=True)),
                ("contract_months", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "fee_per_placement",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "guarantee_days",
                    models.PositiveIntegerField(
                        default=90, help_text="Free replacement period after joining."
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("on_hold", "On hold"),
                            ("filled", "Filled"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="job_orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("submitted", "CV sent"),
                            ("shortlisted", "Shortlisted"),
                            ("interview", "Interview"),
                            ("selected", "Selected"),
                            ("medical", "Medical"),
                            ("visa", "Visa"),
                            ("ticket", "Ticket"),
                            ("deployed", "Joined / deployed"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="submitted",
                        max_length=12,
                    ),
                ),
                ("interview_at", models.DateTimeField(blank=True, null=True)),
                (
                    "offered_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("medical_date", models.DateField(blank=True, null=True)),
                (
                    "medical_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("pending", "Pending"),
                            ("fit", "Fit"),
                            ("unfit", "Unfit"),
                        ],
                        max_length=10,
                    ),
                ),
                ("visa_number", models.CharField(blank=True, max_length=50)),
                ("visa_expiry", models.DateField(blank=True, null=True)),
                ("ticket_date", models.DateField(blank=True, null=True)),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("guarantee_until", models.DateField(blank=True, null=True)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "candidate_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="industry.candidate",
                    ),
                ),
                (
                    "candidate_invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "job_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="industry.joborder",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PlacementCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cost_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical"),
                            ("visa", "Visa"),
                            ("ticket", "Air ticket"),
                            ("agent", "Agent commission"),
                            ("documents", "Documents / attestation"),
                            ("other", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField()),
                ("paid_to", models.CharField(blank=True, max_length=150)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="expenses.expense",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="costs",
                        to="industry.placement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="placement",
            constraint=models.UniqueConstraint(
                fields=("job_order", "candidate"),
                name="one_placement_per_job_candidate",
            ),
        ),
    ]
