# Generated by Django 5.1.4 on 2026-10-03 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0006_recruitment"),
        ("tenants", "0016_membership_branches"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="source",
            field=models.CharField(
                choices=[
                    ("office", "Office"),
                    ("website", "Website"),
                    ("agent", "Sub-agent"),
                    ("referral", "Referral"),
                ],
                default="office",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="joborder",
            name="public_summary",
            field=models.TextField(
                blank=True,
                help_text="What job seekers see. The client's name is never shown.",
            ),
        ),
        migrations.AddField(
            model_name="joborder",
            name="publish_online",
            field=models.BooleanField(
                default=False, help_text="Show this job on the careers website."
            ),
        ),
        migrations.AlterField(
            model_name="placement",
            name="stage",
            field=models.CharField(
                choices=[
                    ("applied", "Applied online"),
                    ("submitted", "CV sent"),
                    ("shortlisted", "Shortlisted"),
                    ("interview", "Interview"),
                    ("selected", "Selected"),
                    ("medical", "Medical"),
                    ("visa", "Visa"),
                    ("ticket", "Ticket"),
                    ("deployed", "Joined / deployed"),
                    ("rejected", "Rejected"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="submitted",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="CareersSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("headline", models.CharField(blank=True, max_length=200)),
                ("about", models.TextField(blank=True)),
                ("services", models.TextField(blank=True, help_text="One per line.")),
                (
                    "countries",
                    models.CharField(
                        blank=True,
                        help_text="Countries you recruit for, e.g. Qatar, UAE, Saudi Arabia.",
                        max_length=255,
                    ),
                ),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "licence",
                    models.CharField(
                        blank=True,
                        help_text="Recruitment licence number, shown in the footer.",
                        max_length=120,
                    ),
                ),
                ("accent_color", models.CharField(default="#0f766e", max_length=7)),
                ("ask_passport", models.BooleanField(default=True)),
                (
                    "allowed_origins",
                    models.TextField(
                        blank=True,
                        help_text="Your own website addresses that may send applications, one per line.",
                    ),
                ),
                ("api_key", models.CharField(max_length=40, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
