# Generated by Django 5.1.4 on 2026-10-03 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_credit_limit_customer_payment_terms_days"),
        ("industry", "0007_careers_site"),
        ("tenants", "0016_membership_branches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("headline", models.CharField(blank=True, max_length=200)),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="Shown above the form, e.g. opening hours.",
                        max_length=255,
                    ),
                ),
                ("accent_color", models.CharField(default="#0f766e", max_length=7)),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("min_notice_hours", models.PositiveSmallIntegerField(default=1)),
                ("max_days_ahead", models.PositiveSmallIntegerField(default=90)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnlineBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("resource", "Booking"),
                            ("table", "Table reservation"),
                            ("event", "Event enquiry"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "item_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="Service or resource chosen.", null=True
                    ),
                ),
                ("item_name", models.CharField(blank=True, max_length=200)),
                ("date", models.DateField()),
                ("time", models.TimeField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("guests", models.PositiveSmallIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("source", models.CharField(blank=True, max_length=120)),
                (
                    "linked",
                    models.CharField(
                        blank=True,
                        help_text="What it became, e.g. booking:12 or reservation:4.",
                        max_length=40,
                    ),
                ),
                ("reply", models.CharField(blank=True, max_length=255)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="customers.customer",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="industry_on_company_27e30f_idx",
                    )
                ],
            },
        ),
    ]
