# Generated by Django 5.1.4 on 2026-10-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0008_online_booking"),
        ("tenants", "0016_membership_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteKit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_id", models.SlugField(max_length=60, unique=True)),
                ("api_key", models.CharField(max_length=48, unique=True)),
                (
                    "allowed_origins",
                    models.TextField(
                        blank=True, help_text="Client website addresses, one per line."
                    ),
                ),
                ("connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_check", models.CharField(blank=True, max_length=255)),
                ("last_check_ok", models.BooleanField(default=False)),
                ("enquiry_enabled", models.BooleanField(default=True)),
                ("accent_color", models.CharField(default="#0f766e", max_length=7)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Admin notes: hosting, logins, domain…"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
