# Generated by Django 5.1.4 on 2026-10-03 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0009_website_kit"),
        ("tenants", "0016_membership_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Website add-on switched on by the platform admin.",
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("fresh", "Fresh"),
                            ("bold", "Bold"),
                            ("elegant", "Elegant"),
                            ("minimal", "Minimal"),
                        ],
                        default="fresh",
                        max_length=12,
                    ),
                ),
                (
                    "font",
                    models.CharField(
                        choices=[
                            ("Inter", "Inter"),
                            ("Poppins", "Poppins"),
                            ("Playfair Display", "Playfair Display"),
                            ("Cairo", "Cairo (Arabic)"),
                            ("Lora", "Lora"),
                            ("Montserrat", "Montserrat"),
                        ],
                        default="Poppins",
                        max_length=30,
                    ),
                ),
                ("primary_color", models.CharField(default="#0f766e", max_length=7)),
                ("accent_color", models.CharField(default="#f59e0b", max_length=7)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="Leave empty to use the company logo.",
                        null=True,
                        upload_to="site_logos/",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="site_heroes/"),
                ),
                ("hero_title", models.CharField(blank=True, max_length=150)),
                ("hero_subtitle", models.CharField(blank=True, max_length=255)),
                ("about", models.TextField(blank=True)),
                (
                    "opening_hours",
                    models.TextField(
                        blank=True,
                        help_text="One line per day or range, e.g. Sat–Thu 10am–11pm",
                    ),
                ),
                ("map_url", models.URLField(blank=True, help_text="Google Maps link")),
                ("whatsapp", models.CharField(blank=True, max_length=30)),
                ("instagram", models.CharField(blank=True, max_length=120)),
                ("facebook", models.CharField(blank=True, max_length=120)),
                ("tiktok", models.CharField(blank=True, max_length=120)),
                ("show_catalogue", models.BooleanField(default=True)),
                ("show_offers", models.BooleanField(default=True)),
                ("show_booking", models.BooleanField(default=True)),
                ("show_careers", models.BooleanField(default=True)),
                ("show_contact", models.BooleanField(default=True)),
                (
                    "custom_domain",
                    models.CharField(
                        blank=True, max_length=253, null=True, unique=True
                    ),
                ),
                (
                    "domain_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No own domain"),
                            ("pending", "Waiting for DNS"),
                            ("live", "Live"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                ("custom_css", models.TextField(blank=True)),
                (
                    "custom_html",
                    models.TextField(
                        blank=True,
                        help_text="Extra section shown above the contact section.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
