# Generated by Django 5.1.4 on 2026-10-04 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_credit_limit_customer_payment_terms_days"),
        ("industry", "0010_site_design"),
        ("inventory", "0008_product_boutique_attributes"),
        ("sales", "0014_online_payments"),
        ("tenants", "0016_membership_branches"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MessMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                (
                    "monthly_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave empty to use the plan's fee.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("ended", "Ended"),
                        ],
                        default="active",
                        max_length=8,
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text="Room, company, food preference…",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mess_memberships",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="MessLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("reason", models.CharField(blank=True, max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="industry.messmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-from_date"],
            },
        ),
        migrations.CreateModel(
            name="MessPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("breakfast", models.BooleanField(default=True)),
                ("lunch", models.BooleanField(default=True)),
                ("dinner", models.BooleanField(default=True)),
                ("monthly_fee", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "leave_refund_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Taken off the next bill for each mess-cut day. 0 = no refund.",
                        max_digits=10,
                    ),
                ),
                (
                    "min_leave_days",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Mess cut counts only when at least this many days in a row.",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="messmember",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="industry.messplan",
            ),
        ),
        migrations.CreateModel(
            name="MessMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("served_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "served_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="industry.messmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "meal"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "date", "meal"), name="one_mess_meal_per_slot"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("leave_days", models.PositiveSmallIntegerField(default=0)),
                (
                    "refund",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="sales.salesinvoice",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="industry.messmember",
                    ),
                ),
            ],
            options={
                "ordering": ["-period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "period"), name="one_mess_bill_per_month"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="messmember",
            constraint=models.UniqueConstraint(
                fields=("company", "number"), name="unique_mess_member_number"
            ),
        ),
    ]
