# Generated by Django 5.1.4 on 2026-10-04 11:35

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0011_mess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitedesign",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_heroes/",
                validators=[apps.common.validators.validate_upload_file],
            ),
        ),
        migrations.AlterField(
            model_name="sitedesign",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Leave empty to use the company logo.",
                null=True,
                upload_to="site_logos/",
                validators=[apps.common.validators.validate_upload_file],
            ),
        ),
    ]
