# Generated by Django 5.1.4 on 2026-10-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0012_upload_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitedesign",
            name="extra_languages",
            field=models.CharField(
                blank=True,
                help_text="Other languages visitors can switch to, comma separated codes.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="sitedesign",
            name="language",
            field=models.CharField(
                default="en", help_text="Main language of the website.", max_length=10
            ),
        ),
    ]
