# Generated by Django 5.1.4 on 2026-10-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("industry", "0014_mess_menu_extras_delivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="messmember",
            name="alt_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
