# Generated by Django 5.1.4 on 2026-09-07 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_code', models.CharField(choices=[('sales', 'Sales Report'), ('purchases', 'Purchase Report'), ('expenses', 'Expense Report'), ('profit_and_loss', 'Profit & Loss'), ('balance_sheet', 'Balance Sheet'), ('trial_balance', 'Trial Balance'), ('cash_flow', 'Cash Flow'), ('stock', 'Stock Report'), ('stock_valuation', 'Stock Valuation'), ('customer_outstanding', 'Customer Outstanding'), ('supplier_outstanding', 'Supplier Outstanding'), ('tax', 'Tax Report')], max_length=30)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], max_length=10)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
