# Generated by Django 6.1 on 2026-09-10 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportexport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='reportexport',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='reportexport',
            name='format',
            field=models.CharField(default='csv', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportexport',
            name='report_code',
            field=models.CharField(max_length=50),
        ),
    ]
