# Generated by Django 5.1.4 on 2026-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchasereturn_journal_entry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
