# Generated by Django 5.1.4 on 2026-09-16 11:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchaseorder_created_at_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='currency',
            field=models.CharField(default='QAR', max_length=3),
        ),
        migrations.AddField(
            model_name='purchase',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='currency',
            field=models.CharField(default='QAR', max_length=3),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, default=Decimal('1'), max_digits=18),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='transaction_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
