# Generated by Django 5.1.4 on 2026-09-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchase_currency_purchase_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
