# Generated by Django 5.1.4 on 2026-09-16 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_purchase_tax_breakdown_purchaseline_tax_amount'),
        ('sales', '0010_salesinvoice_tax_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.taxcode'),
        ),
        migrations.AddField(
            model_name='purchaseline',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
