# Generated by Django 5.1.4 on 2026-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journalentry_accounting__company_daa894_idx_and_more'),
        ('purchases', '0008_purchaseline_tax_code_purchaseline_taxable_amount'),
        ('suppliers', '0002_supplier_payment_terms_days'),
        ('tenants', '0011_backfill_payroll_permission'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'date', 'status'], name='purchases_p_company_2c4ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['company', 'supplier', 'due_date'], name='purchases_p_company_cf0b87_idx'),
        ),
    ]
