# Generated by Django 5.1.4 on 2026-09-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0009_purchase_purchases_p_company_2c4ab7_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goodsreceiptnote",
            name="number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="expected_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="purchasereturn",
            name="number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
