# Generated by Django 5.1.4 on 2026-09-30 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("tenants", "0015_company_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("alert_percent", models.PositiveSmallIntegerField(default=80)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="expenses.expensecategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "category")},
            },
        ),
    ]
