# Generated by Django 5.1.4 on 2026-09-23 08:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('tenants', '0012_companyonboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('talabat', 'Talabat'), ('snoonu', 'Snoonu'), ('rafeeq', 'Rafeeq'), ('deliveroo', 'Deliveroo'), ('custom', 'Custom Provider')], max_length=20)),
                ('webhook_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('store_id', models.CharField(max_length=150)),
                ('api_base_url', models.URLField(blank=True)),
                ('api_key_ciphertext', models.TextField(blank=True)),
                ('api_secret_ciphertext', models.TextField(blank=True)),
                ('webhook_secret_ciphertext', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('test_mode', models.BooleanField(default=True)),
                ('auto_accept_orders', models.BooleanField(default=False)),
                ('commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
            options={
                'unique_together': {('company', 'provider', 'store_id')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_order_id', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('received', 'Received'), ('imported', 'Imported'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='received', max_length=12)),
                ('payload', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_imports', to='restaurant.deliveryintegration')),
                ('restaurant_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.restaurantorder')),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('integration', 'external_order_id')},
            },
        ),
    ]
