# Generated by Django 5.1.4 on 2026-09-29 10:36

from django.db import migrations, models


def mark_existing_lines_sent(apps, schema_editor):
    """Lines on orders already past draft/held were sent in the (only) first round."""
    Order = apps.get_model("restaurant", "RestaurantOrder")
    for order in Order.objects.exclude(status__in=["draft", "held"]).only("id", "updated_at").iterator():
        order.lines.update(kitchen_round=1, sent_at=order.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_restaurant_self_order_and_cancellation"),
    ]

    operations = [
        migrations.AddField(
            model_name="kitchenticket",
            name="kitchen_round",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="restaurantorder",
            name="guests",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurantorder",
            name="tax_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="restaurantorderline",
            name="kitchen_round",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurantorderline",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="service_charge_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Suggested service charge for dine-in bills (%).",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="tax_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="VAT/GST charged on restaurant bills (%). 0 = no tax.",
                max_digits=5,
            ),
        ),
        migrations.RunPython(mark_existing_lines_sent, migrations.RunPython.noop),
    ]
