# Generated by Django 5.1.4 on 2026-09-29 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0006_order_rounds_tax_guests"),
        ("tenants", "0014_company_vat_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantorderline",
            name="offline_line_id",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name="OfflineOrderSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.UUIDField()),
                ("offline_number", models.CharField(max_length=40)),
                ("device_created_at", models.DateTimeField(blank=True, null=True)),
                ("synced_line_ids", models.JSONField(blank=True, default=list)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("synced", "Synced"),
                            ("attention", "Needs attention"),
                        ],
                        default="synced",
                        max_length=12,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_syncs",
                        to="restaurant.restaurantorder",
                    ),
                ),
                (
                    "synced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "client_id"),
                        name="one_sync_per_offline_bill",
                    )
                ],
            },
        ),
    ]
