# Generated by Django 5.1.4 on 2026-10-04 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0007_offline_pos_sync"),
        ("tenants", "0016_membership_branches"),
    ]

    operations = [
        migrations.CreateModel(
            name="StarterSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["company", "kind"],
                        name="restaurant__company_d2ec50_idx",
                    )
                ],
            },
        ),
    ]
