# Generated by Django 5.1.4 on 2026-10-04 10:06

from django.db import migrations, models


def mark_kerala_quick_items(apps, schema_editor):
    from apps.verticals.restaurant.kerala_menu import QUICK
    MenuItem = apps.get_model("restaurant", "RestaurantMenuItem")
    MenuItem.objects.filter(product__sku__in=[f"KL-{code}" for code in QUICK]).update(is_quick=True)


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0008_starter_sample"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantmenuitem",
            name="is_quick",
            field=models.BooleanField(
                default=False,
                help_text="Shown as a big tile on the Quick sale counter.",
            ),
        ),
        migrations.RunPython(mark_kerala_quick_items, migrations.RunPython.noop),
    ]
