# Generated by Django 5.1.4 on 2026-10-04 11:35

import apps.common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0009_menu_item_quick"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurantmenuitem",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="restaurant/menu/%Y/%m/",
                validators=[apps.common.validators.validate_upload_file],
            ),
        ),
    ]
