# Generated by Django 5.1.4 on 2026-10-05 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0010_upload_limits"),
        ("tenants", "0018_backups"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantprofile",
            name="web_auto_accept",
            field=models.BooleanField(
                default=False, help_text="Send website orders straight to the kitchen."
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="web_delivery",
            field=models.BooleanField(
                default=False, help_text="Customers can ask for home delivery."
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="web_note",
            field=models.CharField(
                blank=True,
                help_text="Shown in the cart, e.g. Delivery only in Doha.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="web_orders_enabled",
            field=models.BooleanField(
                default=False, help_text="Show “+ Add” and a cart on the website menu."
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="web_paused",
            field=models.BooleanField(
                default=False,
                help_text="Busy or closed: the cart shows “not taking orders now”.",
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="web_pickup",
            field=models.BooleanField(
                default=True,
                help_text="Customers can order and collect from the restaurant.",
            ),
        ),
        migrations.AddField(
            model_name="restaurantprofile",
            name="web_ready_minutes",
            field=models.PositiveSmallIntegerField(
                default=30, help_text="Usual time until an order is ready."
            ),
        ),
        migrations.CreateModel(
            name="OnlineOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                        ],
                        default="new",
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("delivery", "Delivery")],
                        default="pickup",
                        max_length=10,
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=30)),
                ("address", models.TextField(blank=True)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Website the order came from.",
                        max_length=120,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("reject_reason", models.CharField(blank=True, max_length=255)),
                ("handled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="online",
                        to="restaurant.restaurantorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "status"],
                        name="restaurant__company_14428e_idx",
                    )
                ],
            },
        ),
    ]
