# Generated by Django 5.1.4 on 2026-09-07 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('subscription_expiry', 'Subscription Expiry'), ('payment_due', 'Payment Due'), ('low_stock', 'Low Stock'), ('product_expiry', 'Product Expiry'), ('membership_expiry', 'Membership Expiry'), ('invoice_overdue', 'Invoice Overdue'), ('supplier_payment_due', 'Supplier Payment Due'), ('customer_payment_due', 'Customer Payment Due'), ('general', 'General')], default='general', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('emailed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('subscription_expiry', 'Subscription Expiry'), ('payment_due', 'Payment Due'), ('low_stock', 'Low Stock'), ('product_expiry', 'Product Expiry'), ('membership_expiry', 'Membership Expiry'), ('invoice_overdue', 'Invoice Overdue'), ('supplier_payment_due', 'Supplier Payment Due'), ('customer_payment_due', 'Customer Payment Due'), ('general', 'General')], max_length=30)),
                ('days_before', models.PositiveIntegerField(help_text='For expiry-style notifications: how many days before the event to fire.')),
                ('also_email', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.company')),
            ],
            options={
                'unique_together': {('company', 'notif_type', 'days_before')},
            },
        ),
    ]
