# Generated by Django 5.1.4 on 2026-09-09 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('subscription_expiring', 'Subscription Expiring Soon'), ('subscription_expired', 'Subscription Expired'), ('payment_due', 'Payment Due'), ('low_stock', 'Low Stock'), ('product_expiry', 'Product Expiry'), ('membership_expiry', 'Membership Expiry'), ('invoice_overdue', 'Invoice Overdue'), ('supplier_payment_due', 'Supplier Payment Due'), ('customer_payment_due', 'Customer Payment Due'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='notif_type',
            field=models.CharField(choices=[('subscription_expiring', 'Subscription Expiring Soon'), ('subscription_expired', 'Subscription Expired'), ('payment_due', 'Payment Due'), ('low_stock', 'Low Stock'), ('product_expiry', 'Product Expiry'), ('membership_expiry', 'Membership Expiry'), ('invoice_overdue', 'Invoice Overdue'), ('supplier_payment_due', 'Supplier Payment Due'), ('customer_payment_due', 'Customer Payment Due'), ('general', 'General')], max_length=30),
        ),
    ]
