# Generated by Django 5.1.4 on 2026-09-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_reminder_log_daily_runs"),
        ("tenants", "0015_company_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReportSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "emails",
                    models.TextField(
                        blank=True,
                        help_text="Extra email addresses, comma separated. Owners always get it.",
                    ),
                ),
                ("whatsapp_number", models.CharField(blank=True, max_length=30)),
                ("last_sent_on", models.DateField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "unique_together": {("company",)},
            },
        ),
    ]
